projects/unix/Makefile
https://github.com/ricrpi/mupen64plus-core/commit/1cf54788f636c43de57f6c2f8c8dfc7928332f18
=> Makefile: Add VFP hardfloat as an option

src/main/main.c
See discussion on commit 72e00f1031e78e5527abf959abd42d38e288d42b.
@paulscode
=> Fix bug in framelimiter.

src/ai/ai_controller.c, src/ai/ai_controller.h, src/main/main.c, src/main/main.h, src/main/savestates.c, src/pi/pi_controller.c, src/pi/pi_controller.h, src/r4300/interupt.c, src/r4300/interupt.h, src/r4300/mi_controller.c, src/r4300/mi_controller.h, src/r4300/r4300.c, src/rdp/rdp_core.c, src/rdp/rdp_core.h, src/rsp/rsp_core.c, src/rsp/rsp_core.h, src/si/si_controller.c, src/si/si_controller.h, src/vi/vi_controller.c, src/vi/vi_controller.h
The main feature of this PR is to move several RCP behavior (AI,VI,SI,PI,RSP,RDP) from interupt.c to their respective subsystem.
This should allow better locality of source code.
To be merged after PR #65.
=> Interrupt refactorings

src/r4300/new_dynarec/linkage_arm.S
https://github.com/mupen64plus/mupen64plus-core/issues/72
=> linkage_arm.S: Fix VFP SOFTFP target

projects/msvc11/mupen64plus-core.vcxproj, projects/msvc8/mupen64plus-core.vcproj, projects/unix/Makefile, src/main/main.c, src/pi/pi_controller.c, src/ri/rdram_detection_hack.c, src/ri/rdram_detection_hack.h
Small PR to better isolate rdram detection hack.
=> Rdram detection hack

src/osal/files_unix.c, src/osal/files_win32.c
=> Avoid accessing bytes before *destpath in search_dir_file

src/api/common.c, src/api/config.c, src/main/util.c, src/osd/screenshot.cpp
These should (hopefully) fix the coverity defects with the CID 38101, 38114, 38108, 38109, 38106, 38110
=> Coverity fixes

src/r4300/cached_interp.c
This fixes the performance regression which affects Gauntlet Legend
when played with the old dynarec. The regression has been introduced
in commit 36a1c4fff70fde8cbbc81bbaf44e2fe417b3e620.
=> Don't invalidate cached code if instruction is not compiled.

src/r4300/new_dynarec/x86/assem_x86.c
This also fix DK going through wall issue on x86
https://www.dropbox.com/s/1h7xhqa66et3as1/Donkey%20Kong%2064%20%28U%29%20%5B!%5D.st0?dl=0
=> new_dynarec: Implemented recompiled DMULT instruction on x86

src/r4300/new_dynarec/new_dynarec.c
=> new_dynarec: Avoid replacing an allocated temporary register

src/main/eventloop.c
@conchurnavid this should fix https://github.com/mupen64plus/mupen64plus-core/issues/141,
could you test please?
=> Fixed gfx moveScreen when SDL_VERSION > 1.2

data/mupen64plus.ini, src/main/rom.c, src/main/rom.h, src/vi/vi_controller.c
Taken from https://github.com/libretro/mupen64plus-libretro/commit/9f071ad11e9d0d16ad10950cefd64a1727fa3d26
=> Fix Pokemon Puzzle League

src/ai/ai_controller.c, src/ai/ai_controller.h, src/pi/pi_controller.c, src/r4300/cp0.c, src/r4300/cp0.h, src/r4300/cp1.c, src/r4300/exception.c, src/r4300/interpreter_cop0.def, src/r4300/interpreter_special.def, src/r4300/interpreter_tlb.def, src/r4300/interupt.c, src/r4300/new_dynarec/arm/assem_arm.c, src/r4300/new_dynarec/x86/assem_x86.c, src/r4300/x86/gr4300.c, src/r4300/x86_64/gr4300.c, src/rdp/rdp_core.c, src/rdp/rdp_core.h, src/rsp/rsp_core.c, src/rsp/rsp_core.h, src/si/si_controller.c, src/vi/vi_controller.c
This PR is mostly about avoiding magic constants. There should be no functional changes.
=> Clean magic constants

src/memory/memory.c, src/r4300/interupt.c, src/r4300/new_dynarec/arm/assem_arm.c, src/r4300/new_dynarec/arm/linkage_arm.S, src/r4300/new_dynarec/new_dynarec.c, src/r4300/new_dynarec/x86/assem_x86.c, src/r4300/new_dynarec/x86/linkage_x86.asm
=> Fix new dynarec interrupt management

src/main/util.c
The parameter of isspace should be in the range 0-255.
=> Fix assertion failure when starting Kuiki Uhabi Suigo

src/device/r4300/mi_controller.c, src/device/si/af_rtc.c, src/device/si/eeprom.c, src/device/si/game_controller.c, src/device/si/pif.h, src/main/main.c
Some minor refactorings to remove some magic constants and rework the si peripherals status command handling.
=> Minor refac

data/mupen64plus.ini
These values were taken from Project64 and they don't seem to work here, the game doesn't boot with these settings
=> Fix Indiana Jones

data/mupen64plus.ini
See https://github.com/mupen64plus/mupen64plus-core/issues/145#issuecomment-288199819
=> DK64 Bone Displacement fix

data/mupen64plus.ini
I know you've all been dying to play this title, so I thought I would add a note on how to get it to work. I'm not sure where else this kind of thing could go, so I put it here. Might be helpful in the future to someone that tries to get it working.
=> Add note for NBA Showtime - NBA on NBC

src/main/main.c
Don't reset the speed limiter when falling behind. Instead adjust the time. This prevents unwanted resets when the game is falling behind on slower devices. These resets cause unneeded sleeps on slower devices which make the game run even slower.
See:
https://github.com/mupen64plus/mupen64plus-core/issues/236
This code change was taking from https://github.com/mupen64plus-ae/mupen64plus-ae/blob/d5c5f321548fc4d7a1d72d19364671e3fcc207a5/app/src/main/jni/mupen64plus-audio-sles/main.cpp
A similar fix was made there by me.
=> Don't reset the speed limiter when falling behind

src/device/memory/memory.c, src/device/r4300/mips_instructions.def, src/device/r4300/new_dynarec/arm/linkage_arm.S, src/device/r4300/new_dynarec/x86/linkage_x86.asm, src/device/r4300/x86/dynarec.c, src/device/r4300/x86_64/dynarec.c
https://github.com/mupen64plus/mupen64plus-core/issues/316
=> Fix random resets in South Park 64

data/mupen64plus.ini
Credits to @Nekokabu (from https://github.com/project64/project64/pull/1317)
=> Multiplayer timing fix for Mario Kart E and J

src/device/pi/cart_rom.c, src/device/pi/cart_rom.h
This fixes https://github.com/mupen64plus/mupen64plus-core/issues/311 (International Track & Field 2000 and Midway's Greatest Arcade Hits Vol. 1)
=> Fix write_cart_rom/read_cart_rom

data/mupen64plus.ini
All of these games have some graphical flickering without CountPerOp=1.
=> CountPerOp=1 for Factor5 games

src/device/gb/gb_cart.c, src/device/si/transferpak.c
=> Change tpak/gb debug message level to verbose.

data/mupen64plus.ini
I forgot about the Japanese version of this game.
=> Add setting for Mischief Makers J

src/device/pi/pi_controller.c
This fixes https://github.com/mupen64plus/mupen64plus-core/issues/154
Right now, if the PI controller gets a strange request, we basically just ignore it and hope for better luck next time.
What this change does: If the rom address is too large, or if the rom address is good, but the (rom_address + length) would put us outside the ROM's size, then we copy what fits, and fill the rest with 0's.
I'll do some more testing in the next day or two to make sure this doesn't cause any regressions in other games.
=> Fix duplicate saving in Paper Mario

data/mupen64plus.ini
See https://github.com/mupen64plus/mupen64plus-core/issues/392
=> CountPerOp=1 for Yakouchuu II - Satsujin Kouro

src/osd/screenshot.cpp
Fix for https://github.com/mupen64plus/mupen64plus-core/issues/398
=> Fix screenshots for games with colon in the title

README.md
I added TravisCI and Coverity badges. As I don't know if this has already been discussed before, feel free to refuse this PR if you think it's a bad idea.
=> Add travisCI and coverity badges

data/mupen64plus.ini
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/402
=> Fix save size for Custom Robo V2

data/mupen64plus.ini
You can read about it here:
http://goldeneyevault.com/viewfile.php?id=349
Performs better with CountPerOp=1
=> Add entry for 007 - Goldfinger

data/mupen64plus.ini
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/409
=> Fix slowdowns in Mischief Makers

src/device/r4300/fpu.h
Adapted from https://github.com/project64/project64/commit/c3d89e8fc159c712a8383bb97c031bc84754ff38
Fixes (tested using PeterLemon's test ROM):
https://github.com/mupen64plus/mupen64plus-core/issues/416
=> Fix rounding in interpreter

src/device/memory/memory.c, src/device/memory/memory.h, src/device/rdp/fb.c
This PR does almost the same as PR #477 but doesn't change the dirty page tracking method.
=> Fix FbInfo 2

src/device/cart/cart.c, src/device/cart/cart.h, src/device/cart/cart_rom.c, src/device/cart/cart_rom.h, src/device/device.c, src/device/device.h, src/device/pi/pi_controller.c, src/device/pi/pi_controller.h, src/device/r4300/interrupt.c, src/device/r4300/interrupt.h, src/device/r4300/mi_controller.c, src/device/r4300/mips_instructions.def, src/device/r4300/new_dynarec/new_dynarec.c, src/device/si/cic.c, src/device/si/cic.h, src/device/si/pif.c
This PR is just a collection of preliminary refactoring commits extracted from PR #446. They are not directly related to 64DD so we can incorporate them hopefully sooner.
=> Preliminary refactorings 

src/device/r4300/tlb.c
Needed to resolve build error (on Raspberry Pi 3).
=> Remove orphaned line related to removed GoldenEye TLB hack

projects/VisualStudio2013/mupen64plus-core.vcxproj, projects/VisualStudio2013/mupen64plus-core.vcxproj.filters, projects/unix/Makefile, src/device/gb/gb_cart.c, src/device/gb/gb_cart.h, src/device/gb/m64282fp.c, src/device/gb/m64282fp.h, src/main/main.c, src/main/savestates.c
With this work we get :
- partial support for gb camera (no image capture yet, but may come in the future)
- mbc2 support
- mbc5 rumble support
=> Various GB cart enhancements.

src/main/savestates.c
Fix for https://github.com/mupen64plus/mupen64plus-core/issues/497
Tested and working on my end
=> Fix crash when loading save state

src/main/xxHash/xxhash.c, src/main/xxHash/xxhash.h
Just pulling in the latest xxHash from upstream (https://github.com/Cyan4973/xxHash)
=> Update xxHash to 0.6.4

src/device/r4300/new_dynarec/new_dynarec.c
reported by @fzurita in PR #510
=> Fix compilation of new dynarec.

src/main/savestates.c
Lame attempt at keeping savestate offsets aligned... not really proud of what I've done because it is still very fragile, but should fix current crashes.
Should also probably bump savestate version ? But is it considered a major version bump or minor ?
@Gillou68310 @fzurita can you test if this indeed fixes your crashes ? Thanks
=> Fix: try to keep savestates offsets aligned.

doc/emuwiki-api-doc/Mupen64Plus-Core-Parameters.mediawiki, src/main/eventloop.c
Added the 4 missing Joystick counterparts of the Keyboard Mappings
- Reset
- Speed Down
- Speed Up
- Frame Advance
=> Added missing Joy Mappings

src/main/xxHash/xxhash.c, src/main/xxHash/xxhash.h
https://github.com/Cyan4973/xxHash/releases/tag/v0.6.5
=> Update xxHash to 0.6.5

src/main/savestates.c
This may help fixing some edge-cases of crashes while loading
savetstates.
We isolate the savestate data extraction part from the state committing
part so that curr offset don't depends on external factors which could
lead to crashes.
@fzurita Can you test that to see if it helps with https://github.com/mupen64plus/mupen64plus-core/issues/520 ?
=> Cleanup tpak savestate loading.

projects/VisualStudio2013/mupen64plus-core.vcxproj
To be merged after https://github.com/mupen64plus/mupen64plus-win32-deps/pull/7
=> Update nasm path to use latest stable release 2.13.03

src/device/r4300/new_dynarec/x64/assem_x64.c, src/device/r4300/new_dynarec/x64/assem_x64.h
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/603
=> Fix mingw build

src/api/vidext.c
This fixes https://github.com/mupen64plus/mupen64plus-core/issues/663
In my case, before this fix VSync was always ON in linux and standalone commandline (`--noosd`) mupen64plus.
=> Set VSync (SDL_GL_SetSwapInterval) after GL context is available

subprojects/xxhash/xxh3.h, subprojects/xxhash/xxhash.c, subprojects/xxhash/xxhash.h
Previous version was 0.6.5, changelog can be found here:
https://github.com/Cyan4973/xxHash/releases
=> Update xxHash to 0.7.2

src/device/r4300/interrupt.c, src/device/r4300/interrupt.h, src/device/rcp/vi/vi_controller.c, src/device/rcp/vi/vi_controller.h, src/main/savestates.c
Should fix https://github.com/mupen64plus/mupen64plus-core/issues/554
=> Remove next_vi

data/mupen64plus.ini
Fixes #636 
Won't someone please think of the children and merge this PR
=> CountPerOp=1 for Elmo's Letter Adventure

src/device/r4300/idec.h, src/main/workqueue.h
Fixes issue #712 reported by @mazes-80.
=> Fix multiple definition errors

src/device/r4300/interrupt.c
Integrate work done by @flagrama
=> Fix hard reset crash

src/device/r4300/interrupt.c
Previous commit was incomplete and broke x86 compilation.
=> fix compilation on x86

src/main/netplay.c
You can read about DSCP/QoS here: https://en.wikipedia.org/wiki/Differentiated_services
This tags outgoing UDP packets with "EF" (Expedited Forwarding). This tells the local router that these packets are "realtime" packets and need to be given priority.
I verified that this is working as expected by looking at the traffic in Wireshark after implementing this change:
The effects of this would depend on the users home router. Most "gaming" routers from ASUS or Netgear support QoS based on DSCP tags. Most SMB routers (for instance I use a Ubiquiti EdgeRouter X) also support this.
Since most home Internet plans are quite light on upload speeds, QoS can be helpful to prioritize real time traffic (voice, gaming).
=> Tag outgoing UDP packets with EF DSCP

projects/unix/Makefile
After some struggle and assistance in the 'issues', this was the necessary changes to make the mac stuff build
=> Fix to MacOSX building

src/api/m64p_types.h, src/device/cart/cart.c, src/main/main.c, src/main/rom.c
=> Add prefix to m64p_rom_save_type members

src/device/dd/disk.c
cc @LuigiBlood 
Did what you mentionned in the previous PR. Should be equivalent to previous code.
=> refactor lba_end computation to better convey intent

src/main/main.c, src/main/netplay.c
I wanted to make sure these don't get missed:
https://github.com/mupen64plus/mupen64plus-core/commit/07a22eeff3188b1141c87c26a7a7bba807185241
https://github.com/mupen64plus/mupen64plus-core/commit/a00ba8dca007fdf939b8d83e5090869144f6a12a
@fzurita perhaps you could comment on the results of the speed limiter change? Do you think it could be merged into the upstream code?
=> Netplay fixes from Android port

data/mupen64plus.ini
=> Prevents game freezing unrelated to dynarecs

src/device/rcp/pi/pi_controller.c
Fixes the issue identified in https://github.com/mupen64plus/mupen64plus-core/pull/868#issuecomment-861760293
@m4xw
=> Fix address check for DD DMA Interrupt

src/device/rcp/pi/pi_controller.c
See https://github.com/mupen64plus/mupen64plus-core/commit/c55e48e685944be556fe6c3fd366bdac14e93661
=> Fix for compiler warning

src/main/eventloop.c
I forgot to do this in my previous PR.
=> Add NO_KEYBINDINGS for joy mappings

src/device/cart/is_viewer.c, src/device/cart/is_viewer.h
Fixes a segfault in [The Missing Link](https://www.romhacking.net/hacks/5334/) when entering a door.
=> Fix IS Viewer crash

subprojects/xxhash/xxhash.h
https://github.com/Cyan4973/xxHash/releases/tag/v0.8.1
=> Update xxhash to 0.8.1

data/mupen64plus.ini
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/927
=> CountPerOp=1 for Bottom of the 9th

.github/workflows/build.yml, appveyor.yml, projects/msvc/mupen64plus-core.vcxproj
Depends on: mupen64plus/mupen64plus-win32-deps#12
=> CI/CD: Update MSVC

src/api/m64p_types.h, src/device/r4300/new_dynarec/new_dynarec.c, src/main/rom.c
See https://n64brew.dev/wiki/ROM_Header
=> Add ROM version to m64p_rom_header

src/main/rom.c
This adds support for the save type from the advanced homebrew ROM header (see https://n64brew.dev/wiki/ROM_Header)
=> Add support for Advanced Homebrew ROM Header save type

README, README.md
=> Update README* files

src/device/cart/is_viewer.c, src/device/r4300/cp1.c
=> Fix Big-Endian Incompatibilities

.github/workflows/build.yml
=> ci: install vulkan-headers package in MSYS2

src/api/frontend.c, src/main/rom.c
Corrects implementation of https://github.com/mupen64plus/mupen64plus-core/pull/1059
=> Correct ROM file size checks

src/main/savestates.c
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/1031
=> savestates: Only notify SAVECOMPLETE once save is actually done

src/main/netplay.c
This is a change pulled from @loganmc10's fork of mupen64plus-core.
=> Disable VRU during netplay

src/device/cart/is_viewer.c
Modify it to check each number one by one and whether they sum to overflow.
=> Fix integer overflow in write_is_viewer

.github/workflows/build.yml, .github/workflows/schedule.yml, .github/workflows/scripts/ci_build.sh, .github/workflows/scripts/ci_get_libglew_i386.sh, .github/workflows/scripts/ci_install_ubuntu_deps.sh, projects/unix/Makefile
=> CI/CD: Upgrade & add artifacts with GB Camera support

src/main/netplay.c
I looked at `netplay.c` and think that allocating UDP packets constantly during emulation is very wasteful and rather expensive.
So this patch makes the netplay code re-use the UDP packets, this is allowed in SDL_net:
> https://wiki.libsdl.org/SDL2_net/SDLNet_AllocPacket
> When done with this packet, you can free it with [SDLNet_FreePacket](https://wiki.libsdl.org/SDL2_net/SDLNet_FreePacket). Packets can be reused multiple times; you don't have to allocate a new one for each piece of data you intend to send.
This should hopefully save a few CPU cycles when people are using mupen64plus with netplay.
=> Only allocate UDP packets once

src/device/cart/is_viewer.c
This implements the nits I commented on PR #1123
=> Fix nits from IS viewer buffer overflow patch
