mupen64plus/mupen64plus-core

- projects/unix/Makefile
I attach a commit that adds preliminary unofficial support for compiling the Pure Interpreter and Cached Interpreter for little-endian MIPS as a build target.
I do not have access to a big-endian MIPS host to check its `uname -m` output. It is possible that my proposed stanza compiles for big-endian MIPS as if it were little-endian, if the output includes `mips` (for example `mipseb`). Given the low-level nature of the Core, such an incorrect compilation would give Undefined Behavior on the emulated N64 from the execution of its very first opcode due to its entire address space having the wrong endianness.
> Add a MIPS support stanza for the Unix Makefile

- projects/unix/Makefile
- src/r4300/new_dynarec/linkage_arm.S
-ARMv5 and ARMv6 (like Raspberry PIs CPU) need -DARMv5_ONLY (assem_arm.c). Check CPU and set define if ARMv5 or ARMv6 is present.
-Use gcc macros instead of -DNEON and -DVFP_HARD (linkage_arm.S and Makefile)
-Raspberry PI: Mupen64plus-core is running now with "make VFP_HARD=1 VC=1 OSD=0". Default rice plugin still fails with a core error (SDL_SetVideoMode failed). mupen64plus-video-gles2n64 plugin from ricrpi is working. GLES stuff needs some investigation.
> Raspberry Pi fix and ARM NEON/VFP_HARD cleanup

- src/vi/vi_controller.c
vi->field value is assumed to be either 0 or 1 for VI_CURRENT_REG
update. The previous vi->field update formula did not guarantee that,
and therefore could lead to corrupted VI_CURRENT_REG values.
This regression was introduced in commit f9308ad.
> Fix vi->field update when in interlaced mode.

- src/r4300/interpreter_cop0.def
- src/r4300/interpreter_r4300.def
- src/r4300/interpreter_special.def
- src/r4300/pure_interp.c
- src/r4300/recomp.c
- src/r4300/recomp.h
- src/r4300/reset.c
*This pull request arose from [RFC: Deleting the Hacktarux JIT ("Old Dynarec")](https://groups.google.com/forum/#!topic/mupen64plus/4rOO7cX0toY).*
As of commit 44f1424898a2bdcb23bc11861b35b0e9f9855aca, the Pure Interpreter in mupen64plus simply forwards all opcodes to the Cached Interpreter and asks it to fill `precomp_instr` structures for the opcode at the Program Counter and the next one, then executes the first one with `PC->ops();`.
`PC->ops();` is an [indirect call which mispredicts 100% of the time](http://www.emulators.com/docs/nx25_nostradamus.htm), and the Cached Interpreter uses even more indirectly called functions drawn from arrays, killing performance on chips with large unpredicted branch penalties. In addition to those performance penalties, this also creates unnecessary …
> Decouple the Pure Interpreter from the Cached Interpreter

- projects/msvc10/mupen64plus-core.vcxproj
- projects/msvc10/mupen64plus-core.vcxproj.filters
- projects/unix/Makefile
- src/main/main.c
- src/memory/memory.c
- src/memory/memory.h
- src/r4300/interpreter_r4300.def
- src/r4300/new_dynarec/assem_arm.c
- src/r4300/new_dynarec/assem_x86.c
- src/r4300/new_dynarec/assem_x86.h
- src/r4300/new_dynarec/linkage_arm.S
- src/r4300/new_dynarec/linkage_x86.S
- src/r4300/new_dynarec/linkage_x86.asm
- src/r4300/new_dynarec/new_dynarec.c
- src/r4300/new_dynarec/new_dynarec.h
- src/r4300/x86/gr4300.c
- src/r4300/x86_64/gr4300.c
Here's some instructions In order to build with the new_dynarec on windows:
MSVC2010:
-Open mupen64plus-ui-console solution property page
-Select "Configuration Properties"
-Change mupen64plus-core project configuration to New_Dynarec_Debug or New_Dynarec_Release depending if you're building in Debug or Release mode.
MINGW:
Use "make" with NEW_DYNAREC=1
> Allow building the core with the new dynarec on windows

- projects/msvc11/mupen64plus-core.vcxproj
- projects/msvc8/mupen64plus-core.vcproj
- projects/unix/Makefile
- src/ai/ai_controller.c
- src/ai/ai_controller.h
- src/main/main.c
- src/main/savestates.c
- src/plugin/emulate_speaker_via_audio_plugin.c
- src/plugin/emulate_speaker_via_audio_plugin.h
- src/r4300/interupt.c
With this PR I propose small refactorings (the first 3 commits), and a more ambitious change which isolate the AI subsystem from the audio plugin.
The AI subsystem now expect two callbacks (set_audio_format, push_audio_samples) in order to play audio.
A simple implementation of these 2 callbacks has been done using the audio plugin in order to keep retro-compatibility with existing audio plugin.
@littleguy77 , @twinaphex, @gen2brain, @ricrpi, @Nebuleon :
I'd like your opinions on the 2 new possible callbacks for audio output.
Would it be easy for your frontends to provide their own implementation of these callbacks (in case we deprecate the audio plugin, or if you want to get rid the audio plugin in your frontends) ?
Basically set_audio_format allows you to setup the audio device …
> AI refactorings

- src/r4300/new_dynarec/new_dynarec.c
Super Mario 64 intro was triggering the assert.
I just replicated the behavior found in load_regs_entry.
@Gillou68310 : can you confirm that it this fix makes sense ?
It does work for me, but it is mostly guess work.
> Fix load_regs_bt.

- doc/emuwiki-api-doc/Mupen64Plus_v2.0_Core_Debugger.txt
- doc/emuwiki-api-doc/Mupen64Plus_v2.0_headers.txt
- src/api/debugger.c
- src/api/m64p_debugger.h
- src/api/m64p_types.h
- src/debugger/dbg_breakpoints.c
- src/debugger/debugger.c
- src/debugger/debugger.h
This should help API users properly pass run state values, and improves readability of the run state code.
> Add a m64p_dbg_runstate enum for DebugSetRunState.

- src/main/rom.c
*This pull request is a new version of the defunct pull request #78, with more changes as suggested by @Narann to remove magic constants from the code. I don't think I could switch the branch on the old pull request once it was made...*
main/rom.c's open_rom function does memcpy from the source buffer into the Core's buffer, and then swap_rom on the Core's buffer. With .z64 and .n64 input ROMs, the second pass has to read each word back after the memcpy, and they were likely kicked out of the data cache.
This pull request proposes a one-step operation that copies and swaps bytes from the source buffer into the Core's buffer. It also uses named 4-byte signature arrays to detect an image's endianness.
> Copy and byte-swap incoming N64 ROMs in one step (version 2)

- src/debugger/dbg_decoder.c
I propose two commits to enhance the consistency of the debugger's MIPS disassembler.
First, I add a `$` before the names of all integer registers, not just `$zero`, `$at`, `$gp`, `$sp` and `$ra`.
Second, I split opcodes from their operands by tabs as well as spaces in `r4k_disassemble_split`, because for some reason, the disassembler writes Coprocessor 1 (FPU) opcodes separated from their operands with `'\t'`. So instead of `"mtc1\t\t$a0,$f0"` being parsed as the opcode `"mtc1\t\t$a0,$f0"` with no operands, it now gets correctly parsed as an `mtc1` with `$a0,$f0` as its operands.
Small, but (IMHO) useful.
> Debugger enhancements

- src/r4300/interpreter_r4300.def
I attach a commit that modifies `LWL`, `LWR`, `LDL`, `LDR`, `SWL`, `SWR`, `SDL` and `SDR` to compute masks and bit shift amounts at run time to load and store parts of 32-bit and 64-bit values, instead of having a giant `switch` statement, 3 or 7 branches of which have similar code with different constants.
The main advantages of this are:
* reduced code duplication and source line count;
* reduced code size (when compiled);
* reduced branching or indirect jumping (depending on how the compiler implements a 4- or 8-option `switch`, a series of conditional branches or a jump table).
But there are some disadvantages:
* the code is much more difficult to wrap one's head around when first reading it;
* there is more code to execute unconditionally to compute the masks and bit shifts.
The main …
> Simplify the unaligned memory access opcodes

- src/api/config.c
- src/r4300/interpreter_cop0.def
- src/si/cic.c
This fix for CID 38108 was actually introducing dead code and not fixing the
actual problem. The check for the ftell_result == -1 was already some lines
before.
The CID report was also not about the ftell return value. Sorry about that.
This reverts commit 6c10db91a5f1a13431b9aefabbbc0918ee5ca4b7.
> Revert "Check if the size calculation for config file failed"

- src/r4300/new_dynarec/arm/assem_arm.c
- src/r4300/new_dynarec/x86/assem_x86.c
Hopefully fixes #94. I looked in the new subdirectories of `new_dynarec` and this should fix all inclusion issues.
> Fix New Dynarec build failures arising from commit bdb8a88

- src/r4300/cached_interp.c
I forgot to clear the bits before setting their new value in commit
30b97ee. That could cause problems with non word aligned addresses.
> Fix skip to next block logic in code invalidation.

- src/debugger/dbg_memory.c
- src/main/savestates.c
- src/r4300/cp1.c
- src/r4300/cp1.h
- src/r4300/cp1_private.h
- src/r4300/fpu.h
- src/r4300/interpreter_cop1.def
- src/r4300/interpreter_r4300.def
- src/r4300/new_dynarec/x86/assem_x86.c
- src/r4300/r4300.c
- src/r4300/recomp.c
- src/r4300/x86/assemble.h
- src/r4300/x86/gcop1.c
- src/r4300/x86_64/assemble.h
- src/r4300/x86_64/gcop1.c
These commits are intended to follow up those in #69 and #83 with more decoupling. Each commit has a message that describes it.
I would like some comments on the two following things I saw while making the changes:
1. In [`r4300_reset_hard` of `r4300.c` as of commit ff1b04f](https://github.com/mupen64plus/mupen64plus-core/blob/ff1b04f43e97ee8d2d4203656a1f08aec4768f6b/src/r4300/r4300.c#L95-L154), I've made it so `rounding_mode` was updated by a new function, `update_x86_rounding_mode`. But I saw that the rest of the function is directly accessing variables of the R4300 implementation despite work done in #83 to prevent this. And, what's more, it even accesses the TLB variables directly. **Should I replace the direct accesses in that function as part of this PR? Should there be TLB pointer …
> More decoupling

- src/r4300/new_dynarec/arm/arm_cpu_features.c
GCC 4.8 warns about a format/type mismatch in the sscanf statements.
@Gillou68310 Would you mind reviewing this, since you were the original author?  Is there a reason you were starting with int type and then casting to narrower types?
> Squelch sscanf warning in arm_cpu_features.

- src/r4300/new_dynarec/arm/linkage_arm.S
This fixes issue #119 and was cherry-picked from the Debian packages. Maybe we should also go through the rest of the patches because there are more on https://anonscm.debian.org/cgit/
> Avoid .text relocations in PIC shared library

- projects/unix/Makefile
OpenBSD has consistently had up‐to‐date packages for over three years and four mupen releases now. I’ve actively maintained it the whole time and provided several pull requests which have been merged. I think at this point the warning is no longer necessary.
> Remove unnecessary OpenBSD warning.

- src/r4300/new_dynarec/arm/linkage_arm.S
The "Avoid .text relocations in PIC shared library" patch causes crash at start of Conker's BFD on android. But after cleaning up linkage_arm.S this crash disapears. I'm not sure what fixed the issue but IMO it's either a GCC issue or a code alignement issue.
> Merge back "Avoid .text relocations in PIC shared library" fix + cleanup linkage_arm.S

- data/mupen64plus.ini
The Subscreen Delay Fix for zelda OoT is now in conflict with GLideN64 own subscreen fix.
gonetz/GLideN64#589
> Remove Zelda OoT Subscreen Delay Fix from mupen64plus.ini

- src/r4300/new_dynarec/new_dynarec.c
The delay slot cannot overwrite R0, it's not necessary to make a copy of the branch address register (R0)
> new_dynarec: Fixed bomberman 64

- src/r4300/new_dynarec/arm/assem_arm.c
- src/r4300/new_dynarec/new_dynarec.c
- src/r4300/new_dynarec/x86/assem_x86.c
dyna_linker and dyna_linker_ds are really hard to understand looking at the asm code, so I decided to port both functions to C for better understanding.
Obviously the C functions will run slower than the asm ones, but the difference is unnoticeable even on android devices.
This is beeing tested on paulscode.com for a month without regressions so far.
> Dynamic linker

- src/main/eventloop.c
This is only necessary for angrylion's plugin
> Call gfx moveScreen when SDL window moved (Windows only)

- src/main/main.c
Sometimes a frame takes an excessive amount of time to execute, this usually happens when moving to another zone (ingame loading).
I noticed that the framerate becomes very unstable in this case. Discarding these frames help to get a more stable framerate.
> Framelimiter: Discard frames with excessive execution time

- src/main/main.c
If the speed limiter sleeps for too long, we will sleep for less time the next time around.
This is useful if the sleep period is so short that the application cannot sleep for that short a time which unnecessarily slows down the frame rate.
> Improve speed limiter accuracy

- src/main/main.c
Fixed issue that would cause it to constantly reset if the speed was set
too low.
When this would happen, the game would appear to run way too fast.
> Fix speed limiter issue

- README
- README.md
Goal was to provide a Markdown version of the README for those viewing from GitHub. Also added "custom installation paths" from the original wiki to Section 3 of both of the README files, as well as links to "mupen64plus.org/docs" for documentation.
> Documentation Update and Formatting

- src/api/frontend.c
- src/main/main.c
If a loadstate job is set before emulator is running the loadstate will happen on the first safe state interrupt.
> Allow setting a loadstate job before emulator is running.

- projects/unix/Makefile
- src/main/cheat.c
- src/main/savestates.c
- src/main/savestates.h
- src/r4300/interupt.c
This is needed to make the savestate/cheat code work with GLupeN64 (RetroArch).
RetroArch doesn't use/need SDL, so this protects the SDL calls inside "USE_SDL"
It also exposes savestates_save_m64p/savestates_load_m64p, since RetroArch has its own slot management system.
I'm not sure about Visual Studio, somewhere in there it will need to define USE_SDL for this to work.
> Make SDL usage optional in some files

- data/mupen64plus.ini
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
- src/vi/vi_controller.c
This is meant to resolve https://github.com/mupen64plus/mupen64plus-core/issues/139
These values were taken from Project64's RDB file:
https://github.com/project64/project64/blob/master/Config/Project64.rdb
I assume they came to those values via some testing, but this should probably receive some testing as well before it is merged.
For games that had a ViRefresh value I also made sure the CountPerOp (Counter Factor for PJ64) matched. That includes Beetle Adventure Racing, Indiana Jones and the Infernal Machine, and Nightmare Creatures
> Use custom ViRefresh for some games

- src/si/pif.c
- src/si/pif.h
When a CIC challenge took place in update_pif_write(), the pif ram
contains a bunch 0xFF followed by 0x00 at offsets 46 and 47. Offsets
48 onwards contains the challenge answer.
Then when update_pif_read() is called, the 0xFF bytes are skipped
up to the two 0x00 bytes that increase the channel to 2. Then the
challenge answer is (incorrectly) processed as if it were commands
for the third controller.
This cause issues with the raphnetraw plugin since it modifies pif ram
to store the result or command error flags. This corrupts the response
and leads to challenge failure.
> Avoid processing CIC response pif ram as commands

- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Allow ViRefresh and ViTiming in ROM database to be overridden in mupen64plus.cfg
This makes it easier to search for a correct value for a ROM because we don't have to find the correct ROM in the database.
This was done in the same style as CountPerOp.
> Allow CountPerScan and ViTiming in ROM database to be overridden

- data/mupen64plus.ini
My cart for Kirby 64 (U) has the BK16D 9851 eeprom chip.
The (J) V1.0+V1.1 seem to use sram. The emulator creates .sra, which matches Project64's behavior as well.
> Fix Kirby 64 save size

- src/osd/osd.cpp
The OSD is incompatible with an OpenGL core context. Having it enabled while using a core context causes GL errors and even graphical glitches.
> Disable OSD if OpenGL core context is in use

- src/device/r4300/new_dynarec/arm/assem_arm.c
Include paths were wrong after https://github.com/mupen64plus/mupen64plus-core/pull/227 (or another recent change)
I adjusted some paths with ../../ relative to the src folder too to simplify things (which matched other code I saw).
main/main.h was included twice - I guess the second one could be removed but I left it for now.
> fix include paths / fixes building on arm/neon

- src/osd/osd.cpp
Sorry when I committed this change before I didn't realize I shouldn't be calling SDL directly, but should be going through the VidExt functions.
> Don't use SDL directly

- src/device/r4300/new_dynarec/new_dynarec.c
Just a couple of warning fixes. This generates a lot of output when building due to the amount those macros are used.
> Fix excessive warnings when compiling using clang.

- data/mupen64plus.ini
CountPerScanline=2200 was taken from looking at the Project64 RDB file. After a bit of testing it seems that CountPerOp=3 gives the best performance without any timing issues.
> CountPerOp=3 for CBFD

- src/api/frontend.c
As seen in https://github.com/mupen64plus/mupen64plus-core/blob/b67105b031d51607305376175281078a45bff0c2/src/main/main.h#L48
Correct me if I'm wrong, but it seems like we always used to allocated the full RDRAM size even though the expansion pak was disabled. After the refactor we are allocating just enough.
This is causing a crash when loading and saving save states because we try to copy the full expansion pak size to and from the save state. This pull request fixes the crash.
This is the commit that broke it:
https://github.com/mupen64plus/mupen64plus-core/commit/99d489dbcc4396ff29a1461aff7a01db1ee2940a
> Restore old behavior when allocating memory for RDRAM

- src/device/rsp/rsp_core.c
- src/device/rsp/rsp_core.h
This is not something that should be merged, but I figured since there was code involved a PR would be an easier place to look at it than an Issue. Plus it's awesome.
To boot WDC, you need to use rsp-cxd4 and enable "SupportCPUSemaphoreLock". That, plus this change, should allow WDC to boot. I assume it will also fix Stunt Racer 64 and similar games.
The graphics are messed up (polygons everywhere). I know nothing about how the N64 works or interrupts or anything. This is just the result of me messing around for the last 4-5 days based on things I had read from HatCat/cxd4, angrylion, etc..
I am hoping that this will be a good hint for people much smarter than me @richard42 @bsmiles32 @Gillou68310 @fzurita @cxd4 and that someone will be able to take it from here and get these games …
> Get World Driver Championship booting

- data/mupen64plus.ini
When these were initially committed, I just copied the values from Project64. Given that that change broke Indiana Jones, it's probably best to remove these values. There is no evidence that they make any improvement, so it's safer to remove them.
At least now there is a core option to modify this value, so if someone is so inclined, they could test out different values to see if they make any difference for a particular game.
> Remove custom CountPerScanline values

- data/mupen64plus.ini
During the intro scene, there should be audio. There currently isn't.
Setting CountPerOp=1 fixes the audio (it's not just the intro scene that is missing the audio).
Project64 has the same issue (Counter Factor=1 is the default for them for this game, but if you set it to Counter Factor=2, you lose the audio)
> Fix audio in Star Wars Episode I - Racer

- README.md
Fixed a small formatting error in the README file's markdown that was improperly linking to the Mupen64Plus site.
> README.md URL fix

- src/device/r4300/fpu.h
- src/device/r4300/mips_instructions.def
- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/x86/assem_x86.c
Another step toward global variable free emulation code.
> Pass pointer to fcr31 around in fpu.h functions to avoid usage of g_dev.

- data/mupen64plus.ini
This fixes the audio in the FMV's in RE2. The voices are now back, and the audio is in sync with the video.
I tested the U version. GLideN64 + CXD4 (HLE video). 32-bit Mupen64Plus with new dynarec
> Fix audio in RE2

- data/mupen64plus.ini
- src/device/ai/ai_controller.c
- src/device/ai/ai_controller.h
- src/device/device.c
- src/device/device.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Fixes #285 
This is a combination of these 2 commits:
https://github.com/project64/project64/commit/f24c464f3f8783dd9fdbeeaa21b02658c1340ec3
https://github.com/Azimer/AziAudio/commit/7140f74be33615b4f9c62164e5e7e4d261cc6e48
Firstly, AI_LEN_REG should be a multiple of 8, so I modified ```get_remaining_dma_length``` accordingly. This may fix other audio issues if they exist, I'm not sure. This is what allowed the audio samples to start getting sent to the audio plugin.
Secondly, Twisted Edge has some strange behaviour with AI_DRAM_ADDR_REG, it points to the wrong address. The "FixedAudioPos" hack takes the first AI_DRAM_ADDR_REG value, and uses that for the rest of the game, ignoring future values.
I compared to Project64 and it sounds the same to me.
> Fix Twisted Edge audio

- data/mupen64plus.ini
Every now and then with Twisted Edge Snowboarding, you get an ear full of static instead of proper audio. Setting CountPerScanline=1600 makes it far less likely (it still happens on rare occasion).
> CountPerScanline=1600 for Twisted Edge

- src/device/device.c
- src/device/device.h
- src/device/si/si_controller.c
- src/device/si/si_controller.h
- src/main/main.c
- src/main/main.h
One less global variable used inside the emulation core.
> Avoid usage of global variable g_delay_si.

- src/api/vidext.c
It originally mapped to SDL_GL_SWAP_CONTROL, which was removed in SDL 1.3; whoever wrote this decided to replace it with SDL_RENDERER_PRESENTVSYNC.  However, SDL_RENDERER_PRESENTVSYNC is not a GL attribute: it's a setting used when creating a 2D renderer, which this code doesn't use at all.  If passed to SDL_GL_(Get|Set)Attribute, it'll be interpreted as the SDL_GLattr value which happens to have the same numeric value, 4, namely SDL_GL_BUFFER_SIZE.
This changes the code to use the functions SDL_GL_(Get|Set)SwapInterval instead.
> Fix M64P_GL_SWAP_CONTROL with SDL>=1.3 and no video extension

- projects/VisualStudio2013/mupen64plus-core.vcxproj
- projects/VisualStudio2013/mupen64plus-core.vcxproj.filters
- src/asm_defines/asm_defines.c
- src/device/memory/memory.c
- src/device/memory/memory.h
- src/device/r4300/mips_instructions.def
- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/arm/linkage_arm.S
- src/device/r4300/new_dynarec/new_dynarec.c
- src/device/r4300/new_dynarec/new_dynarec.h
- src/device/r4300/new_dynarec/x86/assem_x86.c
- src/device/r4300/new_dynarec/x86/linkage_x86.asm
- src/device/r4300/r4300_core.c
- src/device/r4300/r4300_core.h
- src/device/r4300/x86/dynarec.c
- src/device/r4300/x86_64/dynarec.c
- src/device/rdp/fb.c
- tools/gen_asm_defines.awk
With this PR I'm trying to remove byte and hword memory accessors as it adds lots of duplication and bloat. I already tried and failed in a previous attempt (PR47). This time, I went much more gradually (each commit is buildable and should be easily inspectable in case of any regression). I left the dword accessors for a later PR as it require some more work, and I'd like this PR to get some testing early. I'm looking especially for testing on the dynarecs (both Hacktarux and new_dynarec).
I'm really looking forward to get this tested and merged ! This is something I've been hoping for some years now :)
> Remove byte and hword accessors

- src/device/r4300/mips_instructions.def
- src/device/r4300/tlb.h
- src/main/savestates.c
Partially fixes #87, but there are probably more potential overflows lurking in there; I didn't go over it too thoroughly.
FYI: In C, integer overflow when adding and multiplying signed integers is undefined, as is shifting any integer by too high a width, and left-shifting a signed integer if it changes the sign.  GCC started performing optimizations based on these a decade ago, but those optimizations don't usually apply in any particular situation, so usually you just get away with it.
But on my system, with clang-802.0.42, Mario 64 actually fails to boot in the interpreter without this patch: it fails the ROM checksum test performed early on (at 0x800001AC).  (Not sure exactly which operation was responsible; I compiled with -fsanitize=undefined, fixed everything that made it crash …
> Fix undefined behavior in the interpreter

- src/device/r4300/interrupt.c
- src/device/rdp/rdp_core.c
- src/device/rsp/rsp_core.c
This is based on work by @bsmiles32 in https://github.com/bsmiles32/mupen64plus-core/commit/a1b6df0800dd86936b8500cb7b731b10ee8d79ac, brought on by debugging https://github.com/mupen64plus/mupen64plus-core/issues/181
I've tested this ever so briefly on a few games like Super Mario 64 and World Driver Champ. I'm just posting this here to get some feedback and perhaps some testing.
I've also posed a few questions in comments in the code that I was a little unclear on, I'd appreciate if anyone has some insight on those lines.
> Trust plugins to trigger SP interrupts

- src/device/r4300/mips_instructions.def
From the r4300i datasheet:
>  This register will decrement on every instruction executed. The values range between a low value determined by the TLB Wired register, and an upper bound of TLBENTRIES-1. The TLB Random register is used to specify the entry in the TLB affected by the TLBWR instruction
Right now, CP0_RANDOM_REG is only updated before a TLB Write (https://github.com/loganmc10/mupen64plus-core/blob/b3b5d5cae1ba97013a54ad8b9410a725b67449aa/src/device/r4300/mips_instructions.def#L1332-L1334) because that is the only time it is really useful.
However, the value can also be read from, so this change updates the value of CP0_RANDOM_REG before it is read.
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/309
> Fix reading CP0_RANDOM_REG

- src/device/r4300/fpu.h
- src/device/r4300/mips_instructions.def
- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/x86/assem_x86.c
Reopening this PR with the hope of fixing the remaining issue with ARM dynarec.
> [WIP] Pass pointer to fcr31 around in fpu.h functions to avoid usage of g_dev.

- src/device/r4300/mips_instructions.def
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/323
(Allows NHL Breakaway 98 and WCW Backstage Assault to boot)
> Add CP0_ERROREPC_REG to MTC0

- projects/unix/Makefile
Otherwise it silently exits with code 127, presumably because the input (binary) is not valid text in the system encoding.
> Fix asm_defines w/ mawk by setting LANG=C

- data/mupen64plus.ini
- src/api/frontend.c
- src/main/main.c
- src/main/main.h
- src/main/rom.c
- src/main/rom.h
This PR does a number of things:
It moves the initialization of (g_)rdram_size from CoreStartup to main_run, with the rest of the config variables. @bsmiles32 I didn't see any need for this to be a global, am I correct in my understanding?
It allows DisableExtraMem to be set in mupen64plus.ini, and enables it for Iggy's Reckin' Balls, where it is required.
> Updates to DisableExtraMem

- src/device/r4300/mips_instructions.def
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/221
This was adapted from:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/TLBclass.cpp#L128-L146
It allows the games mentioned in #221 to boot. I haven't done extensive testing to see if this breaks other games.
> Ignore TLB write if TLB entry is unmapping itself

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/rsp/rsp_core.c
- src/device/rsp/rsp_core.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
PR https://github.com/mupen64plus/mupen64plus-core/pull/307 actually broke a few games (NBA on NBC, Hydro Thunder).
Project64 has a setting/hack called "RSP Audio Signal" https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/MemoryVirtualMem.cpp#L1148-L1152
This fixes games like Hydro Thunder and NBA on NBC. I tested it and it works here as well. It is enabled for: NBA on NBC, Hydro Thunder, Tarzan, and Rugrats in Paris (these games were taken from the Project64 RDB)
Of course we could also revert #307, but I think that was a positive change, it simplified the code and allowed us to remove the strange Perfect Dark hack that was in place, it also fixed freezing in Top Gear Rally 2.
> Implement "Audio Signal"

- src/device/r4300/mips_instructions.def
- src/device/r4300/new_dynarec/new_dynarec.c
Someone can correct me if I'm wrong, but I'm fairly certain that is "2" is supposed to represent the "count_per_op" setting
> Use count_per_op instead of 2

- data/mupen64plus.ini
- src/device/ai/ai_controller.c
- src/device/ai/ai_controller.h
- src/device/device.c
- src/device/device.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
This is an improved version of https://github.com/mupen64plus/mupen64plus-core/pull/342. Please read that for details on the problem that this fixes.
This version is much simpler and doesn't require any changes to the API. Instead of sending all the audio data to the plugin at the beginning of the DMA, we send it piece by piece as the DMA happens. Then, at the end of the DMA, we send whatever is leftover.
This should be a "global solution" that doesn't add any noticeable latency, while still fixing the audio in these games.
> Send audio data to plugin as the DMA drains

- data/mupen64plus.ini
- src/device/si/si_controller.c
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
This fixes the error:
```
Core Warning: two events of type 0x8 in interrupt queue
```
in some games. I've noticed it in Diddy Kong Racing and Mischief Makers (it really spams this message in Mischief Makers).
Anyway they are doing this because they don't know the SI DMA is busy. I added the busy bit, now these errors don't show up anymore.
> Add SI_STATUS_DMA_BUSY

- src/device/pi/pi_controller.c
This fixes AI Shogi 3 and other games.
Before:
After:
See:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/Dma.cpp#L202-L203
> Round PI_WR_LEN_REG up to nearest even number

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/r4300/new_dynarec/new_dynarec.c
- src/device/r4300/r4300_core.c
- src/device/r4300/r4300_core.h
- src/device/r4300/tlb.c
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Yes I know... another game specific hack. Project64 employs a similar hack (they disable TLB for the game).
I also took the opportunity to remove the global variable, and I used the same variable for the GoldenEye, and now Rat Attack, hack.
I'm open to suggestions on variables names, I was never very good at naming things...
> Add hack for Rat Attack!

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/vi/vi_controller.c
- src/device/vi/vi_controller.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
I noticed a while ago (https://github.com/mupen64plus/mupen64plus-core/pull/196#issuecomment-298761293) that this "alternate timing" hack only makes a difference when the result of the calculation makes vi->regs[VI_CURRENT_REG] = 0
I got the idea for "< 40" from this comment: https://github.com/tj90241/cen64/blob/master/vi/controller.c#L83-L87
Sometimes ```vi->next_vi - cp0_regs[CP0_COUNT_REG]``` can actually be a negative number in Pokemon Puzzle League, so we've already passed the VI interrupt when this math is being done, which screws up the calculation.
Anyway I've tested this with a number of games and I don't see any regressions, however it is modifying the VI interrupt system, which is already a little "fragile" as it is, so I will probably do some more testing over the next few …
> Get rid of "alternate VI timing"

- src/device/ai/ai_controller.c
You'll notice this the most if you listen to the intro for Pokemon Puzzle League.
In the current master it is very choppy (I'm talking about the very first thing you hear, before you press start). You'll also notice there are some breaks in the audio while you watch the FMV intro after you push "start".
I listened to other games and they still sound good to me. This may fix other audio issues in games if they exist, but I'm not aware of any specific examples.
> Fix order of operations for AI interrupt timing

- src/device/r4300/new_dynarec/x86/linkage_x86.asm
This allows the x86 new dynarec to compile again. I just switched the order of operations that the compiler was complain against and it allows it to build.
My x86 assembly skill is not strong at all, but you would think that the order of additions should not matter. Can anyone double check this and make sure that south park doesn't restart on its own anymore?
This is for this issue: https://github.com/mupen64plus/mupen64plus-core/issues/316
> Get x86 new dynarec compiling again (when using PIC)

- .travis.yml
The before_install  currently fails on Travis CI with:
The following packages have unmet dependencies:
libsdl2-dev : Depends: libegl1-mesa-dev
Depends: libgles2-mesa-dev
E: Unable to correct problems, you have held broken packages.
This can currently only be solved by using the apt addon to install packages.
> Let travis handle the package installation directly

- data/mupen64plus.ini
- src/device/r4300/tlb.c
- src/main/rom.c
- src/main/rom.h
I think it was a mistake for me to submit this hack earlier. It's not good to add an extra if statement every time ```virtual_to_physical_address``` is called just so this game can (sort of) work.
It seems like some kind of strange timing issue, so hopefully as we get more accurate timing this problem will sort itself out.
> Remove Rat Attack hack

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/vi/vi_controller.c
- src/device/vi/vi_controller.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Right now we default to 1500, which is a pretty close guess.
It's still not great though, for instance, the European version of Pokemon Puzzle League still has audio stuttering, but the USA version is fine. Increasing the count_per_scanline to 1600 fixes the European version of the game.
This change moves away from this "guesswork" system, and calculates the count_per_scanline based on the vi clockrate.
It works pretty well, the audio now works in both the USA and European version of Pokemon Puzzle League. In Resident Evil 2, the audio and video now stay in sync (with CountPerOp=1), without any changes to the scanline setting.
More testing is welcome. I've been testing quite a few games and see no regressions so far.
EDIT: For the curious, in NTSC games, this generally increases the …
> Base count_per_scanline on N64 clockrate

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/rdp/rdp_core.c
- src/device/rsp/rsp_core.c
- src/device/rsp/rsp_core.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
This partially reverts https://github.com/mupen64plus/mupen64plus-core/pull/307
@Gillou68310 brought to my attention that those changes might not be quite right. The main difference here is that we unset TASKDONE/HALT/BROKE at the end of the RSP task, and set them when the interrupt is triggered. This should prevent the "doubling up" of RSP tasks that caused us issues before.
I tested Top Gear Rally 2, which used to freeze when an overlapping SP interrupt was called, it still seems fine. I also tested other "troublesome" games like Pokemon Snap, Kirby, World Driver Championship, they all seem to work well, but I'm hoping for some testing on this.
This also allows us to remove the "audio signal" hack that was added.
> Have emulator signal RSP interrupts again

- projects/VisualStudio2013/mupen64plus-core.vcxproj
- projects/unix/Makefile
- src/device/r4300/mips_instructions.def
- src/device/r4300/recomp.c
- src/device/r4300/recomp_types.h
- src/main/xxHash/xxhash.c
- src/main/xxHash/xxhash.h
You can see some performance benchmarks here (conducted in Java):
https://jpountz.github.io/lz4-java/1.3.0/xxhash-benchmark/
And you and read a bit more about xxHash here:
http://cyan4973.github.io/xxHash/
This should provide a performance improvement in the cached interpreter and dynarecs. xxHash is significantly faster than adler32, while still providing an accurate hash.
> Switch from adler32 to xxHash

- data/mupen64plus.ini
- src/device/device.c
- src/device/device.h
- src/device/si/pif.c
- src/device/si/si_controller.c
- src/device/si/si_controller.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Right now we have the SI interrupt delayed in the majority of cases. The only case I know of where DelaySI needs to be off is Mischief Makers (input doesn't work with it enabled). However, I assume if 1 game has issues, others may as well.
The SI DMA has 2 parts: the DMA itself, and the PIF processing. This PR breaks those 2 steps up (right now they both happen at the beginning of the DMA). So for a DMA write, it does the DMA at the beginning of the DMA, and the PIF processing at the end. For a DMA read, it does the PIF processing at the beginning and the DMA at the end. You get the idea.
This removes the need to disable DelaySI for Mischief Makers. Therefore, I assume this is a more accurate way to represent the DMA, and we can remove the DelaySI option altogether.
I've tested a good …
> Remove DelaySI hack/option

- src/main/main.c
This PR is to address https://github.com/mupen64plus/mupen64plus-core/issues/374
See:
https://github.com/mupen64plus/mupen64plus-core/blob/5c386fd741e776a499b67a8d867fc4cdd8e927d3/src/main/main.c#L140-L146
It's actually using UserDataPath, not UserConfigPath as the default (these happen to be the same if the frontend/user hasn't specified something different for UserConfigPath, but if they have, then they are different. They are always different on Linux)
> Fix description of some core config variables

- src/device/ai/ai_controller.h
- src/device/si/game_controller.c
- src/device/si/game_controller.h
- src/device/si/pif.c
- src/device/si/pif.h
- src/device/si/rumblepak.c
- src/device/si/rumblepak.h
- src/main/main.c
- src/main/savestates.c
Recent development omitted to save several emulated device state
variables. We remedy this by appending them at the end of the savestate
file. When loading older savestate files (<1.2 or pj64) we adopt a best-effort
approach to set the missing state to a reasonnable state. But it may
cause some instability.
> Bump savestate format to 1.2

- src/main/main.c
This should help reduce the input lag as suggested by wareya in issue https://github.com/mupen64plus/mupen64plus-core/issues/164
Be sure to test with `AUDIO_SYNC = False` in audio plugin so that SDL_Delay is only called right before input_polling.
@wareya can you test if it makes a difference for you ?
> SDL_Delay is only called just before input polling.

- src/api/m64p_plugin.h
I just wanted to add a short note about the expected usage of the SP_STATUS_REG register by the RSP and GFX plugins.
Right now, after the RSP plugin calls ProcessDList(), it sets HALT | BROKE | TASKDONE. I am proposing that the RSP plugin sets those bits before calling ProcessDList(), and then the GFX plugin can unset them if it needs.
This will maintain backwards compatibility with current GFX plugins, while still allowing future GFX plugins to modify SP_STATUS_REG if needed
> Add note about SP_STATUS_REG

- projects/unix/Makefile
Needed for new firmwares on Raspbian stretch/ SDL 2.0.6. Also working with recent jessie firmwares.
> Raspberry Pi: use new vendor library names

- src/osal/files_win32.c
Fixes these warnings:
```
../../src/osal/files_win32.c: In function 'osal_mkdirp':
../../src/osal/files_win32.c:86:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if (mypath == NULL)
^~
../../src/osal/files_win32.c:90:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
lastchar = mypath + strlen(mypath) - 1;
^~~~~~~~
../../src/osal/files_win32.c: In function 'osal_get_user_configpath':
../../src/osal/files_win32.c:161:13: warning: variable 'hr' set but not used [-Wunused-but-set-variable]
HRESULT hr = SHGetSpecialFolderLocation(NULL, CSIDL_APPDATA, &pidl);
```
Also there was some inconsistency betweening tabbing/4 spaces, I got rid of the tabs
> Fix a few indentation warnings

- src/device/device.c
- src/device/device.h
- src/device/pi/pi_controller.c
- src/device/r4300/interrupt.c
- src/device/r4300/interrupt.h
- src/device/r4300/r4300_core.c
- src/device/r4300/r4300_core.h
- src/device/si/si_controller.c
- src/main/main.c
This is to address https://github.com/mupen64plus/mupen64plus-core/issues/361
This is ready, but I put the WIP tag because it should get some testing. Right now I've only done very limited testing.
2 easy tests for this: The intro to Smash Bros and Star Wars Ep I Racer. The master hand should pull a random character out of the box, right now it always pulls out Mario. The Ep I Racer intro should either be Anakin or Subulba, right now it's always Subulba.
I added a core option to enable/disable randomizing the interrupt timing. Disabling it will be needed for some scenarios like regression testing, netplay, and possibly TAS runs. I think enabling it by default would be good, since it's more similar to how the N64 operated, assuming there aren't any regressions.
> Randomize PI/SI interrupt timing

- src/main/savestates.c
savestate loading code was trying to poweron rumble pak on a
non-initialized rumble pak.
Now we check that the game is rumble pak compatible (therefore it has
been initialized) before calling the poweron function.
A similar issue was also present for transferpak.
> Fix crash when loading savestate.

- data/mupen64plus.ini
Some PR over the summer has fixed the audio in this game with CountPerOp=2, it used to not work (https://github.com/mupen64plus/mupen64plus-core/pull/272)
The CPU usage in this game is a lot higher with CountPerOp=1, so since there are no more issues with CountPerOp=2, it should be the default again. Hopefully this means I can finally play it on my tablet at full speed!
> Remove CountPerOp=1 for Ep I Racer

- data/mupen64plus.ini
Allows for better performance when using GLideN64. Still needs a fairly quick CPU, but the audio is really bad when using GLideN64 HLE with CountPerOp=2
> CountPerOp=1 for Gauntlet Legends

- src/device/si/si_controller.c
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/452
When I submitted https://github.com/mupen64plus/mupen64plus-core/pull/420 I thought I could simplify the code by just doing the whole DMA transaction right before the interrupt. Mischief Makers still worked so I assumed it was good.
However that change broke the input in Turok. This PR basically reverts back to the old behaviour of doing the SI DMA in 2 stages, however it still uses the DMA_BUSY flags instead of the RD_BUSY flag like it did before.
Tested a few games including Mischief Makers and Turok with no issues
Hoping for a review from @bsmiles32 before merger since he looked over the last PR and has some familiarity with that change.
> Do SI DMA in 2 stages

- src/device/cart/cart.c
- src/device/cart/cart.h
- src/device/cart/flashram.c
- src/device/cart/sram.c
- src/device/cart/sram.h
- src/device/device.c
This will fix https://github.com/mupen64plus/mupen64plus-core/issues/456 once https://github.com/mupen64plus/mupen64plus-core/pull/455 is merged.
The auto-detection scheme we use to detect SRAM/flashram doesn't seem to work with Waialae Country Club.
This change will take the value in ROM_SETTINGS if it can, but still try to fallback to the auto-detection scheme if ROM_SETTINGS doesn't specify the type.
This PR adds support for reading/writing to sram via read_cart_dom2/write_cart_dom2, Waialae Country Club does this.
Finally, it gets rid of read_cart_dom2_dummy/write_cart_dom2_dummy, and maps the whole DOM2 address space to read_cart_dom2/write_cart_dom2. I'm not sure why the dummy functions are there, perhaps someone knows the back story?
So far I've tested Paper Mario and Waialae …
> Add support for SRAM cpu read/write

- src/device/rsp/rsp_core.c
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/462
The 2 other games I know of that need this are Pokemon Snap (picture taking needs it), and Kirby 64 (HUD needs it). They both still work fine.
> Increase Delay DP Interrupt time

- data/mupen64plus.ini
This fixes audio crackling and it seems to keep the audio from randomly playing too fast.
I also added one game and removed CountPerOp=3 from Wave Race 64 - Shindou Edition. CPO=3 makes the game run slower and it isn't required to boot the game anymore.
> CountPerOp=1 for Densha de Go! 64

- src/api/m64p_plugin.h
- src/backends/plugins_compat/input_plugin_compat.c
- src/backends/plugins_compat/plugins_compat.h
- src/main/main.c
- src/main/main.h
- src/plugin/plugin.h
Allow switching controller paks using CONTROLS.Plugin API. Instead of reading the Plugin parameter once at startup, it will constantly be read, like old behavior.
Also, if an invalid pak is selected for a game, it will use "None" instead of the first available. This is more similar to older behavior.
This addresses https://github.com/mupen64plus/mupen64plus-core/issues/445
> Allow switching controller paks using CONTROLS.plugin API

- projects/unix/Makefile
- src/main/cheat.c
- src/main/savestates.c
I added this flag a while ago as the beginning of an effort to make SDL usage optional in the core. It never got very far, other parts of the core still rely on SDL, so there is no use for this flag.
Also, I never actually added the USE_SDL flag to the MSVC project files, so the MSVC version probably hasn't been dealing with the SDL mutex at all.
> Get rid of USE_SDL flag

- src/main/main.c
If an invalid controller pak is selected for a game, use no controller pak instead.
See #445 
This way if a user selects an invalid controller pak, they don't get an unexpected one instead.
> If an invalid controller pak is selected, use NONE instead

- src/device/r4300/mips_instructions.def
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/469
Did similar fixes for other unaligned memory accesses to avoid undefined behavior. But I suspect there are more bugs in there because all these instructions don't look symmetrical...
> Fix LWL, LWR, LDL, LDR, SWL, SWR, SDL, SDR implementations

- src/api/frontend.c
- src/device/device.c
- src/device/memory/memory.c
- src/device/memory/memory.h
- src/device/pifbootrom/pifbootrom.c
- src/device/r4300/r4300_core.c
- src/device/si/pif.h
- src/main/main.c
- src/main/main.h
- src/main/rom.c
- src/plugin/plugin.c
Another try at the memory allocation failure encountered in some Android devices. As this is likely due to a shortage of virtual memory, in this PR we provide a fallback mechanism which requires much less memory.
> Big alloc fallback

- src/device/cart/cart.c
- src/device/cart/cart.h
- src/device/cart/flashram.c
- src/device/cart/flashram.h
- src/device/device.c
- src/device/device.h
- src/main/main.c
- src/main/savestates.c
Default to MX29L1100 as it is the most common one and is what pj64 uses.
I don't understand Japanese, but it looked like Derby Stallion could save stuff so it is a potential fix for https://github.com/mupen64plus/mupen64plus-core/issues/458
Will need some more testing with other flashram games though before being merged.
> Add support for different flashram types.

- src/device/r4300/x86/assemble.h
- src/device/r4300/x86/dynarec.c
- src/device/r4300/x86_64/assemble.h
- src/device/r4300/x86_64/dynarec.c
Edit: There was another regression introduced also during the memory refactoring; handlers array is now indexed with physical addresses instead of physical, so we need to mask higher bits.
So everything should be good now. I used Derby Stallion for testing because it crashed with the dynarec almost instantaneously.
---- Previous message
I'm trying to fix computation of handlers[i].{read,write]32 inside dynarec but not done yet.
*It crashes dynarec for now*
Offsets computation are wrong now because each element of handlers array is sizeof(struct mem_handler), not just sizeof(void*). Given that struct mem_handler is basically 3 pointers we just need to multiply by 3 the array index to fix the computation. At least that is what I think, but doing so seems to crash... so anyone has a …
> Fix handlers[i].{read,write}32 comparison in dynarec.

- src/device/device.c
- src/device/rcp/rdp/rdp_core.c
- src/device/rcp/rdp/rdp_core.h
- src/device/rcp/rsp/rsp_core.c
- src/device/rcp/vi/vi_controller.c
- src/device/rcp/vi/vi_controller.h
- src/main/savestates.c
Right now the hack works like this:
If DPC_STATUS_FREEZE bit is set when RSP task should run, run the RSP task when DPC_STATUS_FREEZE is unset.
This works mostly ok, but we did have to add ```dp->sp->regs[SP_STATUS_REG] &= ~SP_STATUS_YIELD;``` to get Perfect Dark working in LLE, as well as the ```!get_event(&dp->r4300->cp0.q, SP_INT)``` check to get it working in HLE. Also, the "puzzle effect" in Banjo-Kazooie is half-black when using FBInfo in GLideN64.
What this change does:
If DPC_STATUS_FREEZE is set when RSP task should run, still run the RSP task, but delay the DP Interrupt until the DPC_STATUS_FREEZE bit is unset. The RSP should still run even in the RDP is frozen.
If a VI Interrupt happens when DPC_STATUS_FREEZE is set, delay updating the screen until its unset. This should …
> Modify DPC_STATUS_FREEZE hack

- src/device/device.c
- src/device/device.h
- src/device/r4300/new_dynarec/new_dynarec.c
- src/device/r4300/pure_interp.c
- src/device/r4300/r4300_core.c
- src/device/r4300/r4300_core.h
- src/device/r4300/tlb.c
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/447
This will need to be tested on every dynarec/interpreter. I've tested the Pure/Cached Interpreter as well as the 64-bit dynarec. I tested the x86 new dynarec a while ago, but it probably should be tested again. ARM should also be tested ( @fzurita )
The only game that should be affected is GoldenEye, however I did make a change to how the Pure Interpreter works generally.
> Remove GoldenEye TLB hack

- src/device/device.c
- src/device/rcp/pi/pi_controller.c
- src/device/rcp/pi/pi_controller.h
- src/device/rcp/rdp/fb.c
- src/device/rcp/rdp/fb.h
- src/device/rcp/rsp/rsp_core.c
There are a few other instances where the framebuffer might be modified. This tracks reads/writes in the PI and SP DMA's.
If you test the latest master version of GLideN64 with this PR Super Mario 64 no longer freezes.
It exposes another bug with have with the dynarec. When using the Cached Interpreter with FBInfo, you can see Mario's head in the Super Mario 64 intro. If you use the 64-bit dynarec, the head is missing
> Add more FB writes and reads

- src/device/device.c
- src/device/pif/pif.c
- src/device/r4300/interrupt.c
Values comming from CIC at poweron/reset were written too early in PIF
RAM. There was a possibility of them getting overwritten by some SI DMA
requests (such as reading mempaks [Perfect Dark]) during the time window
between PIF_INT and NMI_INT.
Now we delay this until NMI_INT is triggered.
> Fix reset bug introduced in commit 1c01c233.

- src/device/rdram/rdram.c
Since the "regs" member is not available on the r4300_core
structure when enabling ARM DYNAREC, accessing this member
directly will cause compilation errors with this setup.
Signed-off-by: Myy Miouyouyou <myy@miouyouyou.fr>
> Device: RDRAM: Use the R4300 helpers to get the R4300 registers

- src/device/rcp/rdp/fb.c
- src/main/savestates.c
I believe this should fix https://github.com/mupen64plus/mupen64plus-core/issues/489
Doing ```memset(&g_dev.dp.fb, 0, sizeof(g_dev.dp.fb));``` will wipe out ```fb->mem, fb->rdram, fb->r4300```, which is probably what was causing the crash.
Using poweron_fb will only wipe the necessary data
This regression was introduced in https://github.com/mupen64plus/mupen64plus-core/commit/99f00d78a2feec139a60ca7d59fb163daf8029b6
@fzurita perhaps you could test and @bsmiles32 you could review as well?
> Fix potential crash with FBInfo and save states

- projects/unix/Makefile
- src/debugger/dbg_memory.c
This broke with upstream commit 6394c606997f88acfc80de4dff33a4ae2de987b4
"Don't use print_insn_XXX in GDB".
> Fix undefined reference to print_insn_i386 with libopcode >= 2.29

- projects/unix/Makefile
For some reason, recent builds on MinGW are failing, the asm_defines_nasm.h file looks like this:
```
)define offsetof_struct_cached_interp_invalid_code (0x00000000
)define offsetof_struct_r4300_core_cached_interp (0x00000af8
)define offsetof_struct_tlb_LUT_w (0x00400680
)define offsetof_struct_tlb_LUT_r (0x00000680
)define offsetof_struct_tlb_entries (0x00000000
)define offsetof_struct_cp0_tlb (0x000002ec
)define offsetof_struct_cp0_count_per_op (0x000002e8
)define offsetof_struct_cp0_last_addr (0x000002e4
)define offsetof_struct_cp0_next_interrupt (0x00000218
)define offsetof_struct_cp0_regs (0x00000000
)define offsetof_struct_r4300_core_cp0 (0x00900c60
)define offsetof_struct_r4300_core_return_address (0x00000a20
)define offsetof_struct_r4300_core_save_rip (0x00000a18
)define …
```
> Fix compile on MinGW

- src/main/rom.c
If a ROM is not on the database (like ROM hacks), they tend to mostly work, except for the mempak and rumble pak not working. I think that to work more correctly when a ROM is not in the database, we should enable these by default.
> If a ROM is not in the database, use 4 players, enable mempak, and enable rumble pak

- data/mupen64plus.ini
The Vigilante games are very demanding on the CPU. Having CountPerOp=1 makes this even more pronounced.
@AmbientMalice you seem to know a lot of the history behind these settings. Do you know why the Vigilante games have CountPerOp=1? I assume we just copied it over from PJ64
I tested the games briefly and they seem to work the same using CountPerOp=2, but much less CPU usage.
> Remove CountPerOp=1 for Vigilante games

- src/device/rcp/pi/pi_controller.c
This needs more testing, I'll report back once I've tested it more.
Fixes: https://github.com/project64/project64/issues/633
Taz Express tries to do an unaligned PI DMA transfer. Cart addresses must be 2-byte aligned and DRAM address must be 8-byte aligned.
This may/probably will break some ROM hacks (particularly some popular SM64 hacks). They don't work on a real console, and this is one of the main reasons.
> Force alignment of PI DMA

- src/device/r4300/x86/dynarec.c
- src/device/r4300/x86/regcache.c
- src/device/r4300/x86/regcache.h
This is based on @richard42's advice in https://github.com/mupen64plus/mupen64plus-core/issues/542#issuecomment-369840016
Removing the force_32 function does indeed fix Indiana Jones in the x86 dynarec.
I also ran PeterLemon's CPUDSLLV.N64, CPUDSRAV.N64, and CPUDSRLV.N64 test ROM's and we still pass those tests (we passed before this change as well).
I really don't know anything about assembly or the dynarec, I was jus testing/implementing @richard42's suggestion and it seems to work, so I created this PR
> Fix DSLLV in x86 dynarec

- src/device/rcp/rdp/rdp_core.c
- src/device/rcp/rdp/rdp_core.h
I have seen some interest lately in emulating the DPC_CLOCK_REG register. See for example https://github.com/cxd4/rsp/issues/14
This should be a harmless change, we currently don't clear the CLOCK_REG when the game writes DPC_CLR_CLOCK_CTR to DPC_STATUS_REG. Given that some RSP/GFX plugins might start incrementing this register, we should implement clearing it. I know of a few games that write DPC_CLR_CLOCK_CTR (Gauntlet Legends and Taz Express come to mind).
Also, DPC_STATUS_START_GCLK should be set on boot, I'm not aware of any game where this makes a difference though.
Renamed some of the status flags to match what is in rcp.h
> Clear CLOCK_REG when requested

- src/debugger/dbg_memory.c
This was overflowing a u8, causing zeroes to be written most of
the time instead of the intended value.
> Fix write_memory_8

- doc/emuwiki-api-doc/Mupen64Plus-v2.0-API-Versioning.mediawiki
- doc/emuwiki-api-doc/Mupen64Plus-v2.0-Core-Video-Extension.mediawiki
- src/api/api_export.ver
- src/api/m64p_types.h
- src/api/m64p_vidext.h
- src/api/vidext.c
- src/main/version.h
On some platforms (for instance, iOS) the default framebuffer object depends on the surface being rendered to, and might be different from 0.
This is also true for Qt. If the rendering surface is a QOpenGLWidget, the application must call ```GLuint QOpenGLContext::defaultFramebufferObject()``` to get the name of the default FBO. See (http://doc.qt.io/qt-5/qopenglcontext.html#defaultFramebufferObject). If it is a QOpenGLWindow, then the default FBO is "0".
GTK is the same, it doesn't allow rendering into the "0" framebuffer, the application must render into a framebuffer created by GTK. RetroArch does the same thing.
This was recently identified as an issue for the Provenance project (https://github.com/Provenance-Emu/Provenance) which is an iOS app that includes mupen64plus.
@braindx …
> Add VidExt_GL_GetDefaultFramebuffer

- src/api/callbacks.c
When running on iOS simulator, some paths are really long. This was causing mupen64plus core to crash DebugMessage with a buffer overflow when printing out statements related to paths.
> Increase DebugMessage buffer size to prevent overflows

- .travis.yml
- data/mupen64plus.ini
- projects/VisualStudio2013/mupen64plus-core.vcxproj
- projects/VisualStudio2013/mupen64plus-core.vcxproj.filters
- projects/unix/Makefile
- src/backends/api/video_backend.h
- src/backends/dummy_video_backend.c
- src/backends/dummy_video_backend.h
- src/backends/opencv_video_backend.cpp
- src/backends/opencv_video_backend.h
- src/device/gb/gb_cart.c
- src/device/gb/gb_cart.h
- src/device/gb/m64282fp.c
- src/main/main.c
- src/main/savestates.c
Following discussion with @LuigiBlood in PR #446, this PR adds GB camera support.
See commit message for more information.
NOTE: I haven't updated the msvc files yet, I'd like to get some feedback first.
@AntonioND: big thanks for sharing your RE work on the GB camera !
> GB Camera support

- src/main/eventloop.c
- src/main/main.c
As a new mupen64plus user, I struggled with the configuration, due to two major categories of unexpected behavior:
1. Under some circumstances, the configuration was changed and saved even when I specified `--nosaveoptions`, potentially leading to undesired options being persisted in the configuration.
2. The program runs when there is no configuration, and it generates a configuration file, but command-line parameters are not always respected unless the configuration is present first.
I do not yet have a proposed solution for problem 2 above, but this should help for problem 1, at least when `--nosaveoptions` is specified. I would like to first get this patchset accepted, if possible. I will show an example of the problems below. Please let me know if I have not explained things …
> Make --nosaveoptions not ever save options.

- src/device/device.c
I must have missed this when doing commit
9e4a3fb335d374ea5320c3cf257d1987c8b3cab6.
> Fix access to DD_ROM memory pointer.

- src/device/r4300/r4300_core.h
There is still one usage of nameless union in m64p_plugin.h (BUTTONS) but as it is public API changing it would break backward compatibility.
> Avoid nameless union in r4300_core.h (this is a non standard extension)

- src/api/config.c
Currently, if a floating-point configuration value is equal to an
integer, it gets rewritten as an integer.
Example:
The Video-Rice PolygonOffsetFactor parameter is registered in the source
as a float, default 0.0f. When configuration is not initially present
(the first run of the program), the internal type is M64TYPE_FLOAT, so
the core writes the value to the config file as '0.000000' (default
6-digit precision of fprintf). On the next run, the core reads the value
and translates it to M64TYPE_INT and then writes it to the config file
as '0'.
This patch changes the parsing so that floats are preserved as floats
even when they happen to have an integral value. This way, a user
reading the config file has a visual indication of which values may be
set to floating-point values.
> Preserve floating-point configuration values.

- src/main/eventloop.c
During SDL joystick initialization needed for core events hotkeys, the loop of all controllers, in case of a J* hotkey should stop on the last found controller (ex.: for four controllers, should go from J0 to J3, instead of J4).
> Fix joy_max for initialize loop

- doc/emuwiki-api-doc/Mupen64Plus-Core-Parameters.mediawiki
This parameter was removed from the core in 0bcfd3cc7.
> Remove DelaySI from wiki

- src/api/config.c
From the commit message of the second patch:
```
The various ConfigGetParamX() functions can handle string inputs
already, but ConfigGetParameter() rejects such inputs beforehand.
Modify ConfigGetParameter() to validate that a string represents a
numeric value. If so, then ConfigGetParamX() can handle the input.
Factor the checks into a new function to keep them from getting too 
long.
Use case:
Values read from the ui-console command line are always strings, by
necessity. When the config file is empty (or somehow lacking the 
specified parameter), then ui-console cannot know the desired type, so
it defaults to storing the parameter as a string. Without this patch,
this can result in plugin code ignoring a validly-specified
command-line parameter.
Use case:
Without this patch, if a user …
```
> Allow valid interpretations of strings as non-strings

- doc/emuwiki-api-doc/Mupen64Plus-Core-Parameters.mediawiki
- src/device/r4300/new_dynarec/new_dynarec.c
- src/main/main.c
- src/main/savestates.c
That way it can be used when loading save states instead of having speculate recompilation always disabled for compatibility with save states.
> Make stop_after_jal a save state parameter instead of configuration

- src/main/savestates.c
Minor cleanup from last pull request. This disables Speculative recompilation when loading pj64 save states.
> Fixes for last save state update

- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/arm/assem_arm.h
- src/device/r4300/new_dynarec/arm/linkage_arm.S
- src/device/r4300/new_dynarec/arm64/assem_arm64.c
- src/device/r4300/new_dynarec/new_dynarec.c
This implements a fix for a bug in some arm 64 bit CPUs as seen here:
https://github.com/dolphin-emu/dolphin/pull/4204
Also, removed some ANDROID specific code that is no longer needed.
@Gillou68310 you should review this please. I didn't see any performance penalties.
Should we attribute the source of the fix in the code?
> __clear_cache fix for ARM 64 devices plus ANDROID cleanup

- src/api/config.c
Front-ends now ensure that configuration is saved (when desired) before
starting the game.
> do not force saving config when file not present

- src/main/main.c
SDL_PumpEvents is described as:
```
SDL_PumpEvents() gathers all the pending input information from devices and places it in the event queue
```
It is related to the input functions. In the past, mupen64plus-ae has used a slightly modified version of SDL2, but now I am trying to update it to use a vanilla version of 2.0.8, however it crashes when calling SDL_PumpEvents(). Presumably because there is no keyboard and SDL_INIT_JOYSTICK is never called. The input subsystem is not setup.
I moved SDL_PumpEvents to the beginning of the ```GetKeys()``` function in input-sdl. I tested using a keyboard and a joystick, both in-game inputs and events (like pause/quit game) still work with keyboard or joystick. See https://github.com/mupen64plus/mupen64plus-input-sdl/pull/68
> Don't call SDL_PumpEvents() in core

- src/device/rcp/vi/vi_controller.c
See: https://en.wikipedia.org/wiki/PAL-M
>It is unique among analog TV systems in that it combines the 525-line 30 frames-per-second System M with the PAL colour encoding system (using very nearly the NTSC colour subcarrier frequency), unlike all other countries which pair PAL with 625-line systems and NTSC with 525-line systems.
> MPAL's refresh rate is 60 Hz

- src/device/rcp/rdp/rdp_core.c
As noted here:
https://github.com/libretro/mupen64plus-libretro-nx/commit/8c87b431e0fe447d7bf2e3666623ee1e57ca80f3
DPC_STATUS_START_VALID and DPC_STATUS_END_VALID are never cleared, causing problems with some LLE RSP plugins
> Don't set DPC_STATUS_START/END_VALID bits

- src/device/rcp/vi/vi_controller.c
- src/device/rcp/vi/vi_controller.h
Not sure if this affects any commercial roms, but it at least enables certain homebrew roms to display something (like some of [these test roms](https://github.com/PeterLemon/N64))
> Fix VI interrupt not being called in certain cases

- src/main/main.c
This caused more problems than it solved, and it sounds like mupen64plus-ae has stubbed out SDL anyway
This reverts commit 87b1946868472d739a58eca69261634970e8537a.
https://github.com/mupen64plus/mupen64plus-core/pull/550
> Revert "Don't call SDL_PumpEvents() in core"

- src/device/rcp/pi/pi_controller.c
This PR fixes:
https://github.com/mupen64plus/mupen64plus-core/issues/600
Cart and DRAM addresses were aligned to fix an issue in Taz Express:
https://github.com/mupen64plus/mupen64plus-core/pull/541
However, this broke saving in Command & Conquer. I tried a couple things, like just aligned PI DMA Writes, Command & Conquer wouldn't boot at all then.
The thing that makes both games (Taz and C&C) work is just aligning the cart addresses.
I'll admit that I don't really understand why, the documentation says:
> We summarize restrictions on DMA transfers as follows:
> 1) RDRAM address must be 8-byte aligned---the three least significant bits of address
must be zeroes.
> 2) BSD address must be 2-byte aligned---the least significant bit of address must be zero.
> 3) Length of DMA must be a …
> Only align cart address in PI DMA

- src/device/r4300/mips_instructions.def
I was testing these test ROMs:
https://github.com/PeterLemon/N64/tree/master/CPUTest
We pass all the CPU tests except for division.
I took this implementation from https://github.com/n64dev/cen64/pull/79. So credit to @sp1187 for this code.
After this PR, all the division test ROMs pass. The only commercial game that I know of that consistently tries to do division by zero is Toy Story 2 (it currently spits out a bunch of "DIV by zero" warnings). I tested that game and it still seems to work fine.
```rrs32 == INT32_MIN && rrt32 == -1``` is a special case, the result of that equation is actually an integer overflow, which was crashing the emulator, so it needs to be dealt with in an if statement, same as the cen64 implementation.
> Proper handling of divide by zero

- src/device/dd/dd_controller.c
Excessive logging can really kill performance (depending on the frontend).
The DD controller is currently printing out a lot of logs just for things like DMA reads and writes. This converts the logs to "verbose" mode, so they'll only print out if you have verbose mode enabled
> Change some DD logging to only happen in verbose mode

- src/device/r4300/cached_interp.c
- src/device/r4300/cp0.c
- src/device/r4300/cp0.h
- src/device/r4300/interrupt.c
- src/device/r4300/mips_instructions.def
- src/device/r4300/new_dynarec/new_dynarec.c
- src/device/r4300/pure_interp.c
- src/device/r4300/x86/assemble.h
- src/device/r4300/x86/dynarec.c
- src/device/r4300/x86_64/assemble.h
- src/device/r4300/x86_64/dynarec.c
- src/device/rcp/ai/ai_controller.c
- src/device/rcp/mi/mi_controller.c
- src/main/savestates.c
@loganmc10 
I didn't realized it at first but https://github.com/mupen64plus/mupen64plus-core/pull/701 is breaking the new dynarec very badly.
The main limitation is that the number of cycles between current cycle count and next interrupt event cannot exceed 2^31
I reworked interrupt scheduling a bit:
- cp0_next_interrupt is now a negative number representing the
number of cycles left until next interrupt is taken.
Next interrupt is taken whether cp0_next_interrupt value is positive or null
- Special interrupt is now a fake interrupt which porpose is
to ensure the number of cycles between current cycle count
and next interrupt will never exceed 2^31
I still need to fix both dynarecs.
In the meantime this PR needs to be tested to see if there's no regression
> Rework interrupt scheduling

- data/mupen64plus.ini
Thanks to @m4xw for helping me track down the correct memory addresses.
Obviously not the correct fix, but at least this won't dirty up the main emulation code. Tested with the U and E versions
> Use cheat code to allow Rat Attack to boot

- src/device/gb/gb_cart.c
Is there any reason why transfer pak writes are disabled? As far as I can tell, it's as simple as the change I did in this pull request.
I can understand why 64DD writes are disabled, but I think we could write it when emulation stops instead of writing the whole file every single write.
With this change, I was able to load a game boy RAM file, make some changes in pokemon stadium 2, save the changes, load the RAM file in a gamebody emulator in Pokemon Gold and I checked that the changes were applied.
> Enable transferpak write

- src/device/r4300/interrupt.c
- src/device/r4300/interrupt.h
- src/device/rcp/ai/ai_controller.c
- src/device/rcp/vi/vi_controller.c
- src/main/savestates.c
Right now we use the "count" of the next event to check if that type of event is pending.
This could lead to the (admittedly rare) situation where the next event is scheduled at COUNT_REG 0, and get_event() would return the incorrect answer.
> Don't check event count to test if event is pending

- src/device/rcp/rdp/fb.c
Right now FBInfo doesn't work properly on either dynarec, see:
https://github.com/mupen64plus/mupen64plus-core/issues/493
https://github.com/mupen64plus/mupen64plus-core/issues/214
It's better to not advertise support for FBInfo at all if it isn't working, since plugins like GLideN64 have it enabled by default for certain games.
From my testing it works pretty reliably with the interpreters
> Disable FBInfo support for dynarecs

- src/api/config.c
This keeps the mupen64plus.cfg config file documented when setting the defaults.
Useful for Retropie (and similar) that has a scripted install for mupen64plus, setting a bunch of defaults. Since config help text does not get populated until the first time mupen64plus is run successfully, it led to these defaults being forever undocumented in the .cfg.
> if config parameter already exists, add help text if missing, before returning successfully

- src/device/dd/dd_controller.c
I believe the formula for DD DMA timing (length * 63 / 25) was taken from MAME:
https://github.com/mamedev/mame/blob/master/src/mame/machine/n64.cpp#L1573
They say "Measured as between 2.53 cycles per byte and 2.55 cycles per byte". 63/25 is 2.52.
We time our interrupts using the COUNT register, which increments at 1/2 the clock speed. To me this means we should be using 63/50.
This change allows F-Zero DD expansion to boot, before it was just sitting on the "DD Loading" screen. The only other game I have tested it the "Dawn to Dusk" Zelda OoT homebrew that was recently released.
The rest of the DD games should be tested to make sure there aren't regressions, I haven't found a really good way to boot them because of the requirement for a cartridge ROM. Maybe someone that knows how to get …
> Adjust DD DMA timing

- src/device/rcp/rdp/fb.c
I noticed that Resident Evil 2 does this, triggering an "Unknown mask" warning
> Support FBWrites with a size of 3

- src/device/r4300/mips_instructions.def
See https://github.com/n64dev/cen64/pull/116
Allows Donkey Kong 64 (U) [f2] (https://github.com/mupen64plus/mupen64plus-core/issues/732) to boot using Pure Interpreter + Angrylion. Game still doesn't work with Cached Interpreter
> IP0 and IP1 CAUSE bits are writeable

- data/mupen64plus.ini
These games are very sensitive to interrupt timing, since https://github.com/mupen64plus/mupen64plus-core/commit/5a1491505f65f7bdef8930d03f9890f6d7992145 they aren't booting.
I don't think it's really the fault of that PR, it's just that the interrupt timing changed a bit and now these games don't like it.
For whatever reason, the (E) version doesn't have this issue
> BattleTanx (U) games need CountPerOp=3 to boot

- data/mupen64plus.ini
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/570
I went to play this game today, it froze (sound but a black screen) just when about to start the first level. Settings CountPerOp=1 fixed the issue, it also happens to fix https://github.com/mupen64plus/mupen64plus-core/issues/570, which is an old reported issue
> CountPerOp=1 for Battle for Naboo

- projects/msvc/mupen64plus-core.vcxproj
I was trying to build mupen64 with VisualStudio 2015 following the instructions for 'Compiling Mupen64Plus in Windows' found at https://mupen64plus.org/wiki/index.php?title=CompilingOnWindows.  The build works for everything, but was failing on building:
mupen64plus-github\mupen64plus-core\src\device\r4300\x86\dyna_start.asm
because the full path had spaces in it, when path expansion occurred the command to compile would complain that more than 1 input file was specified.  This fix just puts quotes around the %(FullPath) variables in the *.vcxproj file to ensure that this doesn't happen. After doing this, I was able to compile everything with no issues.
> Fix path expansion when building with VisualStudio so directories with spaces will not cause the build to fail.

- data/mupen64plus.ini
These games perform much better with CountPerOp=1, it becomes very apparent if you listen to the audio during a race in both games (very choppy with CountPerOp=2)
Both games by the same developer, they behave very similarly.
> CountPerOp=1 for Top Gear Overdrive/Hyperbike

- projects/unix/Makefile
I think we can safely remove this warning now - ARM is a well established target for mupen64plus. i note the same warning isn't there for aarch64.
> Removed "not officially supported" for ARM

- src/device/rcp/rdp/rdp_core.c
Some games bypass the RSP, and use the CPU to send commands directly to the RDP. FlappyBird64 is an example. The current unprotect/protect FB code only occurs in RSP rendering, so FBInfo doesn't work with these types of games.
This change fixes that and allows FBInfo to work with FlappyBird64, which is required for it to render properly in GLideN64
> Enable FBInfo for CPU-RDP rendering

- src/device/rcp/pi/pi_controller.c
Just like in the RSP DMA:
https://github.com/mupen64plus/mupen64plus-core/blob/master/src/device/rcp/rsp/rsp_core.c#L49
The dram address should be masked, I came across one of the PeterLemon test ROMs that attempts a PI DMA using an address that needs to be masked. I believe the reason for this is that the memory can be accessed via cached/un-cached paths, but the resulting address access should be the same
> Mask DRAM address in PI DMA

- src/device/controllers/game_controller.c
I was troubleshooting an issue with netplay raw input, and came across this discrepancy in the way mempak CRCs are calculated.
From http://hcs64.com/files/n64-hw.dox
> when something is not plugged into the
mempack port, then the CRC is calculated the same way except the final
8-bit result is NOT'd. You might wonder why there would even be a CRC
when reading from the mempack port and nothing is plugged in.  Well
basically when nothing is plugged in, data is still read, but it is not
valid data. This data is usually all 0's. The data CRC algo is still
calculated but the result is of course NOT'd to let you know that the
data is erronous.
I have verified this behaviour against a "raw" controller using Raphnet's plugin
> NOT mempak checksum when pak is not present

- src/api/frontend.c
As already discussed at [mupen64plus-input-sdl#91](https://github.com/mupen64plus/mupen64plus-input-sdl/pull/91) it's currently not possible for the frontend to use SDL while Mupen64Plus is running. This is because `CoreShutdown` calls `SDL_Quit` resulting in segfaults if the frontend continues to call SDL functions.
SDL's documentation states that `SDL_InitSubsystem()` and `SDL_QuitSubsystem()` calls are reference counted (`SDL_Init()` is just an alias for `SDL_InitSubsystem()`). `SDL_Quit()` on the other hand does not care about the reference count and shuts everything down no matter what.
I added a check to `CoreShutdown` to only shutdown SDL if it wasn't already initialized at the time `CoreStartup()` was called. That way SDL cleanup is left to the frontend if it's using SDL. In any …
> Allow frontends to manage SDL's lifetime

- projects/unix/Makefile
- src/device/r4300/cp1.c
- src/device/r4300/cp1.h
- src/device/r4300/r4300_core.c
- src/osal/preproc.h
Fixes (only for SSE, not ARM) #724 
The c.eq functions are meant to compare 2 float (or double) values. Computers aren't very good at comparing floating numbers, and the emulator seems to return ```equal``` when the N64 expects the values to be ```not equal```.
Using memcmp seems to work properly, the emulator still passes the PeterLemon/krom N64 test ROM for CP1 C EQ functions, and Rayman/Donald Duck collision detection is fixed
> Disable FTZ (flush to zero) mode for SSE when FS bit is set

- src/device/device.c
- src/device/r4300/cp0.h
- src/device/r4300/interrupt.c
- src/device/r4300/interrupt.h
- src/device/rcp/rsp/rsp_core.c
- src/device/rcp/rsp/rsp_core.h
- src/main/savestates.c
I modelled the FIFO queue after the AI FIFO queue. There is not actually an interrupt that happens at the end of the DMA, but I've used the interrupt/event queue to schedule the end of the DMA, since that is the most convenient way.
I haven't noticed any difference in any game, either an improvement or a regression. As suggested, most games just check DMA_BUSY to see if the DMA is complete, since we never set that bit in our current code, games probably just assume the DMA was _really fast_. This should get us a little closer to timing accuracy, since the games will wait a bit for the DMA to complete, like on a real N64
> Emulate RSP DMA FIFO queue

- data/mupen64plus.ini
See https://github.com/loganmc10/m64p/issues/57. CountPerOp=3 is needed for the game to get past the Nintendo logo
> CountPerOp=3 for Wave Race 64 - Shindou Edition

- projects/msvc/mupen64plus-core.vcxproj
Example:
`msbuild mupen64plus-core.vcxproj /p:Configuration=New_Dynarec_Debug;Platform=x64;PlatformToolset=ClangCL`
Edit:
- Don't set `*TargetPlatformVersion` if it's not strictly necessary, like in VS2015's case
- Apparently `PlatformToolset` always initializes as `v100` (VS2010). Initialization based on `ToolsVersion` value?
> Allow to set custom platform toolset from commands

- projects/unix/Makefile
This patch fixes:
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [Makefile:726: targets] Error 1
```
when running `make`
> Makefile: add missing "

- doc/emuwiki-api-doc/Mupen64Plus-v2.0-Core-Front-End.mediawiki
Not the most substantive of changes :), but I've been reading through the recent netplay-related changes and noticed this typo.
> Fix typo in M64CMD_NETPLAY_INIT docs

- src/device/device.c
- src/device/pif/pif.c
- src/device/pif/pif.h
- src/device/rcp/si/si_controller.c
- src/device/rcp/si/si_controller.h
Here is another DMA flag fix, similar to #721 . As is the case with that PR, I haven't actually come across a game that does a CPU write to PIF RAM, but the documentation is clear:
```dma_busy indicates a DMA is in progress (or an IO write operation)```
```dma_busy is set for all dma and io write operations```
```DMA and IO writes generate an si_interrupt upon completion to inform host software that the operation has concluded.```
I would really love to find a game that does this so I can verify this behaviour, I'll probably keep trying to find an example, unless somebody has a way to search through game ASM code for SW operations to the PIF RAM address.
> Implement PIF write flags properly

- data/mupen64plus.ini
See a discussion here for the benefits of CountPerOp=1 for Smash: http://forum.pj64-emu.com/showthread.php?t=8856
It decreases input latency and I guess puts it more in line with a console, Smash players are really serious about input latency.
Also included Smash Remix (https://github.com/JSsixtyfour/smashremix/releases) in the INI file
> CountPerOp=1 for Smash

- src/api/frontend.c
- src/main/main.c
The current code blocks all cheats during netplay. This also includes hacks from mupen64plus.ini . mupen64plus.ini currently includes a hack to fix Mario Kart multiplayer timing.
This revision just blocks the frontend from enabling cheats, but allows hacks included in mupen64plus.ini to be applied. This is OK since it won't cause desyncs (every client will apply the same hack).
> Just stop frontend from enabling cheats during netplay

- src/main/netplay.c
When I wrote the netplay code I neglected to clean up the linked list used to store the local input buffer.
This just frees any items in the linked list when netplay is closed
> Clean up netplay linked list

- src/device/cart/cart.c
- src/device/cart/flashram.c
- src/device/cart/flashram.h
- src/main/savestates.c
By combining the following sources :
- reverse engineering of Majoras Mask flashram functions [1]
- @sanni's cart reader [2]
- and MX29L1611 datasheet ("close enough" flash memory from Macronix)
I was able to figure a better model for flashram than what we currently
have. As this new modeling of flashram doesn't match one-to-one with
old model, meaning it may possibly "break" older savestate (in fact it may break if the savestate has been taken during some flashram operation, otherwise it should be relatively safe),
I had to bump savestate version.
[1] pending PR in https://github.com/n64decomp/majora/
[2] https://github.com/sanni/cartreader/blob/master/Cart_Reader/N64.ino
I've tested mostly Majora's Mask, Jet Force Gemini and Derby Stallion and it seems to work OK.
If you want to test …
> Rework flashram implementation

- src/device/r4300/new_dynarec/new_dynarec.c
There is a small typo in src/device/r4300/new_dynarec/new_dynarec.c.
Should read `unconditional` rather than `unconditonal`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, unconditonal -> unconditional

- src/backends/api/storage_backend.h
- src/backends/file_storage.c
- src/backends/file_storage.h
- src/device/cart/eeprom.c
- src/device/cart/flashram.c
- src/device/cart/sram.c
- src/device/controllers/paks/mempak.c
- src/device/dd/dd_controller.c
- src/device/dd/disk.c
- src/device/gb/gb_cart.c
- src/main/util.c
- src/main/util.h
- src/osal/files.h
- src/osal/files_unix.c
- src/osal/files_win32.c
This features allows to notify storage backends about the range of modified bytes, and in turn allow them to not have to do a full data write every time save method is called, reducing the saving bandwidth requirement.
This was needed to handle 64DD saves which are several order of magnitude bigger than existing saves.
See https://github.com/bsmiles32/mupen64plus-core/tree/wip_64dd_save for possible usage of this feature.
I'd like to have this merge quickly (in the next few days), so please test and voice your concerns if any.
cc : @richard42, @loganmc10, @fzurita
> storage backend save method nows know about modified byte range

- src/device/dd/disk.c
It only impacted SDK format but there were serious regressions where games just didn't work properly. It seems I didn't do proper testing. Now they do.
Basically when you run Mario Artist Paint Studio, and try to access 2D Paint mode (the first on the left) and it would return Error 23 (Unrecovered Read Error), which is definitely weird. Other games were also impacted in weird ways so that was pretty annoying.
> [Disk] Make sure the wrong System Data is checked upon read of the System Area

- data/mupen64plus.ini
> Remove CountPerOp=1 for Dino Planet

- src/device/memory/memory.c
Port from https://github.com/libretro/mupen64plus-libretro-nx/commit/29ffb30c7f133d3fdff7b80dd0b0f63a9fa9e96e#diff-bf40cfecf6b954a6a6074a40e19efbb0bdc1a4997ec7f014dce41647d8a9038a
@m4xw can you review this and let me know if it looks right? I believe this is sort of step 1 to allowing Parallel RDP to work upstream. If there is anything else that needs to happen in the core (besides a Vulkan interface) please let me know
> Align memory for parallel-rdp

- data/mupen64plus.ini
Reverts mupen64plus/mupen64plus-core#853. Indiana Jones doesn't boots with CountPerOp=1 if a save file doesn't exist.
> Revert "Prevents game freezing unrelated to dynarecs"

- src/device/rcp/pi/pi_controller.c
- src/device/rcp/pi/pi_controller.h
Taken from: https://github.com/n64dev/cen64/blob/master/pi/controller.c
Tested using: https://github.com/PeterLemon/N64/tree/master/CPUTest/DMAAlignment-PI-cart
Before:
After:
There are still 2 tests that fail here that pass on CEN64: https://github.com/n64dev/cen64/pull/200. However, I couldn't get those tests to pass without breaking the graphics in AI Shougi 3, so I left it at the point where AI Shougi 3 would work. AI Shougi 3 graphics are messed up in CEN64, so I assume there is still more work to be done on their implementation.
> Update PI DMA alignment as per CEN64

- src/device/rcp/rsp/rsp_core.c
Taken from: https://github.com/n64dev/cen64/blob/master/rsp/interface.c
Tested using: https://github.com/PeterLemon/N64/tree/master/RSPTest/DMAAlignment-SP
Before:
After:
With these changes, we achieve the same compatibility as CEN64
> Update RSP alignment code as per CEN64

- src/api/config.c
- src/device/r4300/new_dynarec/arm/arm_cpu_features.c
- src/device/r4300/new_dynarec/recomp_dbg.c
- src/device/r4300/recomp.c
- src/main/rom.c
- src/main/savestates.c
- src/main/screenshot.c
- src/main/util.c
- src/osal/files.h
- src/osal/files_macos.c
- src/osal/files_unix.c
- src/osal/files_win32.c
- tools/r4300prof.c
- tools/savestate_convert.c
In order for Windows to support Unicode characters, it needs to use the _w versions of the functions (_wfopen and gzopen_w for example).
Right now mupen64plus doesn't support referencing files on Windows that are in a path containing non-Latin characters, this PR fixes that problem.
> Support Unicode on Windows

- data/mupen64plus.ini
Xena (E) doesn't boot currently, needs CountPerOp=4. Obviously it's not the best solution, but the game seems to run OK and the in-game count down timer seems to be fairly accurate
> Get Xena (E) to boot

- src/device/r4300/r4300_core.c
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/738
@Gillou68310 @bsmiles32 @richard42 
I'd appreciate some feedback to ensure I've done the right thing here (I think I have).
libdragon seems to have a habit of accessing memory using the 0x8.... address and the 0xa.... address interchangeably.
In the other calls to ```invalidate_r4300_cached_code```, both addresses are invalidated, but not in ```r4300_write_aligned_(d)word```.
This allows libdragon software like Flappy Bird to function. I didn't see any negative side affects with other games.
> invalidate alternate address on write

- src/main/main.c
CountPerOp is (along with DisableExtraMem) one of the settings that have to be often changed between games (and sometimes even while playing the same game to resolve bugs). However, it is inexplicably located near the bottom. I placed it higher up, next to DisableExtraMem.
EnableDebugger was located between the two save slot options, I placed it lower.
I believe these changes not only make more sense when working with the config by itself, more importantly they also help with user experience in those downstream GUI projects that render their settings menu by reading the config from top to bottom.
> Rearranged order of Core settings in the config file

- src/device/cart/flashram.c
Saving in Pokemon Puzzle League is currently broken. No .fla file is created at all.
It was broken by: https://github.com/mupen64plus/mupen64plus-core/commit/6049618def04148ae8c6ab3146fd87882231df71
This commit restores this line (using the new logic):
https://github.com/mupen64plus/mupen64plus-core/commit/6049618def04148ae8c6ab3146fd87882231df71#diff-af6d71b286c633a07adc8703bbbb9f229f697dcd1c913aafad1a592d61492205L90
This makes Pokemon Puzzle League saving work again.
I checked a few other Flash RAM games (Command & Conquer, Pokemon Stadium, JFG, Paper Mario) and they are all still working normally. @bsmiles32 I'd really like to hear your feedback on this if possible
> Fix Pokemon Puzzle League saving

- src/device/rcp/pi/pi_controller.c
The DMA Address check fix only worked for reads but writes did not trigger dd_update_bm, and therefore no interrupts were issued
I made it check the entire buffer space so there's no room for errors: It works.
> Fix 64DD Write Address Check Regression

- projects/msvc/mupen64plus-core.vcxproj
- projects/msvc/mupen64plus-core.vcxproj.filters
- projects/unix/Makefile
- src/device/cart/is_viewer.c
- src/device/cart/is_viewer.h
- src/device/device.c
- src/device/device.h
IS-Viewer 64 was a physical debugging tool (https://n64squid.com/homebrew/n64-sdk/development-hardware/). CEN64 has had support for a while (https://github.com/n64dev/cen64/blob/master/pi/is_viewer.c). I referenced/copied their implementation for mupen64plus.
When a ROM has IS64 support, the output is printed as a DebugMessage:
This is used today by homebrew ROM developers to debug their games.
I don't think this should interfere with any existing games. The address space is inside ```dom1 addr2``` (cart ROM), but I map the IS Viewer before the cart ROM. As I understand it, if the current ROM includes that address space, it'll overwrite the IS Viewer mapping. @bsmiles32
> IS Viewer support

- src/device/r4300/new_dynarec/x64/assem_x64.c
- src/device/r4300/new_dynarec/x86/assem_x86.c
@loganmc10 This is basically a no brain fix. The whole function is unreadable and need a major refactoring. I'm not even sure all cases are correctly handled right now...
Anyway this should do it for the time being.
The issue was a missing pop register, leading to stack growing indefinitely.
> Fix https://github.com/mupen64plus/mupen64plus-core/issues/889

- projects/unix/Makefile
- src/main/eventloop.c
This adds an option to allow a front-end to ship a mupen64plus build without any keybindings.
> Add KEYBINDINGS=0 option to Makefile

- projects/unix/Makefile
Re-do of #908 with squashed commits.
I made some basic switches in the Makefile so now it's possible to build and run on macOS without Rosetta 2.
Without knowing maintainer plans, I have it display a warning that arm64 (not aarch64) is not officially supported. If project leadership wishes to officially support this configuration, recommended as this is Apple's architecture going forward, we can remove the warning.
I made an effort to support assembly functionality for the new dynarec as part of #831, but it is either beyond my abilities or not feasible at this time. Regardless, the emulator passes the tests without this element, so I am presuming there is no drawback to releasing with NO_ASM for darwin-arm64.
> Native Apple Silicon (darwin-arm64) Support

- src/device/controllers/paks/mempak.c
- src/device/controllers/paks/mempak.h
- src/main/main.c
- src/main/util.c
- src/main/util.h
- also better conform to expected factory formatted state
according to @bryc research
- unique mempak ID is based on xoshiro256++ PRNG seeded with current
time. This should prove good enough for our purpose, while still being
simple to implement.
- added endian aware serialization primitives (loosely modeled after http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2827.htm)
- added xoshiro256++ PRNG functions
> Generate unique mempaks ID when formatting them

- src/main/main.c
I hadn't thought of this for the mempak PR, but I think there is a small possibility of netplay desyncs because of the randomized mempak IDs.
If the mempak save file already exists, it won't be a problem, because netplay will sync P1's mempak with the other players, but if no mempak save file exists, netplay will just let each player create their own file.
Because of this randomization, each mempak will be slightly different. I don't know if this would cause desyncs, because I can't say for sure if a game reads a mempak to create some RNG or something.
This PR uses a constant seed for generating the mempak ID when netplay is active.
@bsmiles32
> Use a predictable seed when using netplay

- doc/emuwiki-api-doc/Mupen64Plus-v2.0-headers.mediawiki
- src/api/m64p_types.h
- src/device/dd/disk.h
- src/main/main.c
This adds a function called `set_dd_rom_region` to the media loader, allowing frontends to easily switch 64DD ROM based on DD disk region.
> Allow frontends to know what DD ROM region they should use

- projects/unix/Makefile
clang built mingw doesn't support -Bsymbolic
or version scripts unfortunetly
Signed-off-by: Zach Bacon <zachbacon@vba-m.com>
> Add support for clang/mingw targets

- src/main/main.c
As described in my comment on [PR #920](https://github.com/mupen64plus/mupen64plus-core/pull/920#issuecomment-1159220266).
> This PR seems to have introduced a runtime error where `dd_rom_size` can now be uninitialized in the `main_run` function because `load_dd_rom` has been moved inside the branch and executed only if `load_dd_disk` succeeds.
> It seems `init_device` relies on `dd_rom_size` being correctly initialized later, so this seems to introduce a random chance of incorrect behavior based on whether `dd_rom_size` happens to be 0 or not.
> I haven't actually ran into the error myself, but MSVC's debugger caught this pretty quickly on the Debug configuration and would not allow me to run further until it was fixed.
> The obvious solution to me seems to just handle the else case on …
> Initialize dd_rom_size to 0 if load_dd_disk fails to fix possible runtime errors during initialization

- data/mupen64plus.ini
- doc/emuwiki-api-doc/Mupen64Plus-v2.0-API-Versioning.mediawiki
- doc/emuwiki-api-doc/Mupen64Plus-v2.0-Plugin-API.mediawiki
- projects/msvc/mupen64plus-core.vcxproj
- projects/msvc/mupen64plus-core.vcxproj.filters
- projects/unix/Makefile
- src/api/frontend.c
- src/api/m64p_plugin.h
- src/api/m64p_types.h
- src/backends/api/joybus.h
- src/device/controllers/game_controller.c
- src/device/controllers/vru_controller.c
- src/device/controllers/vru_controller.h
- src/device/device.c
- src/device/device.h
- src/device/rcp/ai/ai_controller.c
- src/device/rcp/ai/ai_controller.h
- src/main/main.c
- src/main/rom.c
- src/main/rom.h
- src/main/savestates.c
- src/plugin/plugin.c
- src/plugin/plugin.h
https://youtu.be/6_iPf8ZC_3M
* Windows build of m64p with VRU support: https://drive.google.com/file/d/1ZarcKEHs0ZpNhtan0QatjdIOPhxCP3S1/view?usp=sharing
* Linux: https://drive.google.com/file/d/191vE6ZoghRPGHdyUUnClEYaeA0onBz-1/view?usp=sharing
You can see the other changes that were made (to the input plugin) by looking at this branch: https://github.com/loganmc10/m64p/tree/vru
* VRU Support
- Only 2 games support the VRU: Hey You Pikachu, and Densha de Go! (English translation: https://www.romhacking.net/translations/2947/ also supports the VRU)
- Might not be perfect. I don't own a physical VRU, so all this work was done based on what zoinkity wrote and what I could get from the programming manual, and from trying to match the behaviour I saw on YouTube playthroughs).
- This is an HLE …
> VRU support and Hey You Pikachu audio fix

- src/device/rcp/ai/ai_controller.c
The 3 least significant bits of the AI_LEN register are expected to be 0.
See this test ROM:
https://www.dropbox.com/sh/am52g0hpfqh71ll/AACKhhfaijdnH1gsFAaSjr0ia/lossless?dl=0&subfolder_nav_tracking=1
Audio doesn't work without this fix
Ares: https://github.com/ares-emulator/ares/blob/3767568cdbe0ad7f18782c2bd03e022b8feec841/ares/n64/ai/io.cpp#L36
CEN64: https://github.com/n64dev/cen64/blob/73ad38ca3fe1fcf46362158ac1c088cda52f0cf0/ai/controller.c#L217
> 3 LSBs of AI Length must be 0

- src/device/cart/cart.c
The cartridge should return 0x80 if EEPROM is absent, the same as it does when a controller is absent:
https://github.com/mupen64plus/mupen64plus-core/blob/300cd1e9175d7ab744a64fbf8a7786cefca668a3/src/device/controllers/game_controller.c#L191
This allows Powerpuff Girls, The - Chemical X-Traction to boot. This game doesn't support saving, but seems to specifically ensure that EEPROM is absent before booting.
> Proper response when eeprom absent

- src/api/vidext_sdl2_compat.h
Fix wrong pitch argument in call to `SDL_CreateRGBSurfaceFrom` in SDL 1.2 compatibility code for `SDL_SetVideoMode`.
`SDL_CreateRGBSurfaceFrom` wants an argument `pitch` that is the number of bytes per scan line in the surface. Previously, 0 was passed as the pitch and it worked. However, as of SDL 2.24, this is not accepted anymore, which results in a crash of the emulator.
> Fix crash due to SDL_SetVideoMode in SDL 2 compatibility code.

- src/main/main.c
- src/main/main.h
- src/main/savestates.c
This makes mupen64plus-core use the ROM's MD5 for the save filename, this makes more sense because let's assume you have a patched ROM, the GoodName will be `Game (Unknown ROM)`, now let's assume you have another patched ROM that uses the same base game, then the saves of patched ROM 1 will show up in patched ROM 2, which is undesired and will most likely break stuff.
> use MD5 for save filename

- src/main/main.c
When compiling with `OSD=0`, `OnScreenDisplay` is `True` in the configuration file and `video_plugin_render_callback` is called with `0`, then taking a screenshot will fail.
This patch fixes that issue, I do wonder if I should extend this patch to guard every OSD function call with a `#ifdef M64P_OSD` to prevent it having to access the `OnScreenDisplay` option in the configuration file?
> Fix screenshots when compiling with OSD=0

- src/device/dd/dd_controller.c
- src/device/dd/dd_controller.h
- src/device/device.c
- src/device/r4300/cp0.h
- src/device/r4300/interrupt.c
- src/device/r4300/interrupt.h
- src/device/rcp/pi/pi_controller.c
This adds two new interrupt handlers for the two different kinds of interrupts the 64DD can issue (MECHA and BM), then introduces delays based on clock speed (and CountPerOp, kinda to make sure), to every command, but especially the Seek command, and then changes the nature of BM interrupts to work with delays instead of working as fast as possible based on DMAs and other hacky reads.
The timing used is very approximate and is trying to be close to real hardware, but is not quite there, a lot more finetuning will be done eventually, but libleo is very tolerant.
This fixes Gnat Attack in Mario Artist Paint Studio prototype, as the game tries to read the next stage data before unloading the current stage, but since the 64DD responds way too quick it replaces the data before it actually …
> Improve 64DD emulation

- src/main/main.c
- src/main/util.c
- src/main/util.h
This patch fixes an issue where i.e on windows, certain characters like `:<>"/\|?*` aren't allowed to be used for filenames, causing mupen64plus to be unable to create a save, this issue mainly occurs when a ROM/ROM hack isn't in the database and it uses the internal ROM name for the filename, I could make this patch windows-only mostly but to make the filenames consistent across platforms I think it makes sense to do it for all platforms.
> Sanitize save filename

- src/device/dd/dd_controller.c
Fixes F-Zero X Expansion Kit's insanely weird & slow loading times while Paint Studio prototype's Gnat Attack still works.
I completely missed this because I didn't think F-Zero X Expansion Kit would be this affected.
I am pretty certain these timings, while rough, were good enough because it comes from my own tests with real hardware, and are currently used in Ares, I think the insanely slow load times of F-Zero X Expansion Kit are caused by other weird timing problems in the emulator. This PR would at least make F-Zero X Expansion Kit actually playable, because I really cannot be bothered to find the root cause.
> [64DD] Shorten extra cycles timing depending on motor state for stability

- src/main/main.c
This introduces a new setting called `SaveFilenameFormat`, allowing users to choose what filename format they'd like their save games/states in, the 2 options are ROM header name and the Automatic option, this feature has been requested by GhostlyDark and another RMG user (see https://github.com/Rosalie241/RMG/issues/122) due to them creating ROM hacks and it's handy for them to be able to disable the hash appended to the save state/game filenames so saves are available through development without them having to rename it constantly.
> Introduce SaveFilenameFormat parameter

- src/api/vidext.c
Adds an SDL hint to address DPI scaling issues on Windows using mupen64plus-ui-console, rendering windowed resolutions larger than intended. Requires SDL2 v2.24 or newer to work.
No changes made to the high DPI settings for mupen64plus.exe running at 1280x960 windowed resolution.
Using a Desktop resolution of 3840x2160 with 200% scaling.
Upstream:
PR:
> vidext.c: Fix DPI scaling issues on Windows

- src/device/device.c
- src/device/rdram/rdram.c
Fixes an in-game crash in Paper Mario when hitting a specific tree with a hammer.
You can reproduce it with this save state (just hit B on the tree):  
[paper_mario_crash.zip](https://github.com/mupen64plus/mupen64plus-core/files/11782215/paper_mario_crash.zip)
on the N64, `0x0800000-0x03EFFFFF` are mapped, but reads/writes are ignored, see the n64brew documentation: https://n64brew.dev/wiki/RDRAM_Interface#Memory_addressing
> Implement unused RDRAM address range 0x0800000-0x03EFFFFF

- src/device/rdram/rdram.c
Fix pulled from Logan's mupen64plus-core fork.
> Ensure out of bounds RDRAM reads 0

- src/device/rdram/rdram.c
Xeno Crisis has a custom IPL3 so this error should be a warning.
> Change IPL3 memory detection error to a warning

- projects/unix/Makefile
- src/debugger/dbg_memory.c
libbfd 2.39 and onward changed the `INIT_DISASSEMBLE_INFO` to take four arguments.
Continues the ugly hack to use `string -v` output.
> Fix building with libbfd >=2.39

- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/arm64/assem_arm64.c
- src/device/r4300/new_dynarec/x64/assem_x64.c
- src/device/r4300/new_dynarec/x86/assem_x86.c
This patch fix the new dynarec crashes on ARM and ARM64 platforms since the interpreter accuracy improvements, a RMG user reported it a while back and I made this experimental patch for it which fixes it (tested it on my pinebook pro aswell).
I had no idea the new dynarec called the FPU functions from `fpu.h`, and for some reason it kept working fine on x86_64, so I didn't notice it at all until the report came in from a RMG user, after some discussion with @m4xw, he said that we could best wait for @Gillou68310 to come up with a proper patch, but that was a while ago already, so to correct my mistake, I'm offering my patch, which could be improved later by Gillou if he wants to, but it fixes the crashes *now* instead of later, so users who are trying the latest git version of mupen64plus …
> new_dynarec: fix FPU crashes

- src/backends/plugins_compat/input_plugin_compat.c
- src/main/main.c
- src/main/netplay.c
- src/main/netplay.h
This is an upstreaming of the netplay code in simple64.
Notably:
* rdram_size needs to be set after `netplay_sync_settings`, so that it has the proper value for `disable_extra_mem`
* `main_speedlimiter_toggle` should be disabled when netplay is active
* A new packet type is added, `UDP_RECEIVE_KEY_INFO_GRATUITOUS`, which is when the server sends input data without being asked by the player. 
* Currently, the system checks for desyncs every second. Now, it is every 10 seconds (done in order to reduce network traffic, it's not really important to detect desyncs that quickly)
> netplay fixes from simple64

- src/device/cart/is_viewer.c
Process new lines in buffer to prevent empty debug messages without losing data.
Current method wipes out everything after a new line if a new line is not placed at the end of the string. The OoT debug build has many of these so this is very annoying when working with the decomp code of it.
No idea if it would be accurate to how the IS64 actually works, but fixes the broken functionality at least.
> Fix IS64 Truncating Lines

- src/main/rom.c
Otherwise we get a use after free when loading ROMs after a core shutdown + startup.
> rom: Fix closing the ROM database

- src/device/cart/is_viewer.c
After re-reading the code, I realized that using strcpy is a bad idea and we should use memchr instead to add some safety so strcpy doesn't read out of bounds accidentally.
> use memchr instead of strchr in is_viewer.c

- src/main/netplay.c
CS4 is "real-time interactive" and is more appropriate for gaming. The current marking (EF) is usually used for voice calls
> use CS4 for netplay DSCP

- .gitignore
- projects/unix/Makefile
The fix described [here](https://github.com/mupen64plus/mupen64plus-core/pull/1038#issuecomment-1715357695).
Also edited a couple of the` $(LIBOPCODES_MINOR) -ge X` comparisons since they seemed to be comparing against the wrong number according to the comment `(we check for >= 2.28 and >= 2.39)`
> bfd version check fix for X.XX version number format

- src/osal/files.h
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/937
> Fix incorrect OSAL_DIR_SEPARATORS when compiling using mingw

- src/main/main.c
This can be used for particularly demanding game sections when coupled with 60 FPS cheats to ensure greater framerate stability, at the cost of increased CPU utilization.
For reference, 1964GEPD supports values up to 18. Even with an overclock factor of 18, there is still ample room to run above fullspeed on an i9-13900K on Perfect Dark, so a value of 20 should run well on today's high-end CPUs.
This limit of 20 also matches the value used in Project64: https://github.com/project64/project64/blob/dafa1fb24d50e4e8de09fe14a98696a4f71f4c1b/Source/Project64-core/N64System/Enhancement/Enhancement.cpp#L358-L370
PS: Is there a way to test custom ViRefresh without having to modify the ROM database? https://github.com/mupen64plus/mupen64plus-core/pull/204 seems to only source ViRefresh from the …
> Increase maximum allowed overclocking factor to 20

- src/api/frontend.c
Fix for https://github.com/mupen64plus/mupen64plus-core/issues/1049.
Issue 2 could be fixed like this:
```plaintext
if Z64 format:
no divisibility requirements
else if V64 format:
ROM size must be divisible by 2
else if N64 format:
ROM size must be divisible by 4
```
but in `CoreDoCommand` we don't have any information regarding file format (magic bytes are read in `open_rom`, after `ParamInt` validation). Because of that I just assumed that all ROMs sizes must be divisible by 4. If there are valid ROMs not meeting this criteria then either:
- some padding could be added to these ROM files (to make their size divisible by 4), or
- emulator utilizing m64p-core (such as RMG) could calculate ROM buffer size like this: `buffer_size = (rom_file_size + 3) & -4` (ROM size rounded up to the …
> Add missing ROM file size checks

- src/device/r4300/new_dynarec/new_dynarec.c
This is needed on other platforms too, but may be implicit in some where including it again is harmless.
> src: fix the new_dynarec with musl

- src/device/rcp/rsp/rsp_core.c
Ported from:
https://gitlab.com/parallel-launcher/parallel-n64/-/commit/4f7b8a6081f7d02bac26e041f1baf5d5e91875f2
https://gitlab.com/parallel-launcher/parallel-n64/-/commit/3052f79c162a232301fdf725038f813c1ec02edb
https://gitlab.com/parallel-launcher/parallel-n64/-/commit/f379d606e4dd000b72ae90273a1b1874b51f5307
https://gitlab.com/parallel-launcher/parallel-n64/-/commit/07ce4bfd7528cde68939ad2ce1a06c2c7029ec15#06a9a5c035040370b6d9d811526d9586179b3176_52_52
Reference:
https://github.com/libretro/parallel-rsp/pull/10
> RSP opcode fixes

- src/api/frontend.c
- src/main/main.c
- src/main/main.h
This adds support for the PIF ROMs provided by Ares, and this resets the PIF by resetting `g_start_address` after emulation, so a front-end can toggle the PIF ROM without having to shutdown & startup the core.
> Add support for new PIF ROM and reset PIF

- src/device/r4300/new_dynarec/new_dynarec.c
So, currently https://ootmm.com/ works with said libretro core but crashes when transitioning between games with upstream m64p. I narrowed it down to this commit: https://github.com/libretro/mupen64plus-libretro-nx/commit/9cbe0fedf18ee13874ac3361ad013c41806fe4c7
With this change I can confirm it switches without crashes:
[Screencast from 2024-07-05 18-26-14.webm](https://github.com/mupen64plus/mupen64plus-core/assets/1510457/b0db0a13-9d51-4df9-ae49-5f02cd9bd0d2)
Disclaimer: I don't know if it makes sense, this is their commit unchanged (except for code style fixes)
> Backport mupen64plus-libretro-nx dynarec fix for OoTMM randomizer

- src/device/r4300/cp1.c
This matches the original version of the code (9644b14f96ddddf34c9cdfedc9d11fc61dc8ffab). In C, the '&' operator occurs after the '^' operator, meaning that the result of `i & 1 ^ 1` is always 0.
> Fix operator precedence in some big-endian code.

- projects/unix/Makefile
* Drops SDL1 support for the unix Makefile since it is unmaintained upstream and using it will result in a degraded experience especially when it receives so little testing. It also makes the SDL section of the Makefile far more complicated than it needs to be.
* Use pkg-config for SDl2. Using sdl2-config hasn't been required for a long time and using pkg-config is preferable for distros.
As a benefit this avoids `which(1)` as a dependency when `PKG_CONFIG` is explicitly set by the user as is the case with some distros.
> build: drop SDL1 support + use pkg-config for SDL2

- README
- README.md
- src/api/vidext.c
- src/main/eventloop.c
- src/main/netplay.c
- src/main/sdl_key_converter.h
- src/main/workqueue.c
- src/osd/osd.c
Per https://github.com/mupen64plus/mupen64plus-core/pull/1093#issuecomment-2434092128 this should remove all checks and code required for SDL versions older than SDL 2.0.0.
> Require SDL2

- src/plugin/dummy_input.c
- src/plugin/dummy_input.h
- src/plugin/plugin.c
Fixes a compiler warning when building with `-Wall -Wextra`
> Add missing VRU dummyinput function definitions

- src/device/dd/dd_controller.c
This fixes the following compiler warning:
```
CC  _obj/device/dd/dd_controller.o
../../src/device/dd/dd_controller.c: In function ‘write_dd_regs’:
../../src/device/dd/dd_controller.c:512:30: warning: taking the absolute value of unsigned type ‘unsigned int’ has no effect [-Wabsolute-value]
512 |             cycles += 4825 * abs(track - old_track);
|                              ^~~
../../src/device/dd/dd_controller.c:547:30: warning: taking the absolute value of unsigned type ‘unsigned int’ has no effect [-Wabsolute-value]
547 |             cycles += 4825 * abs(track - old_track);
|               
```
I've asked @LuigiBlood for advice on what to change and this is the result of that.
> Fix abs() warning in dd_controller.c

- src/device/rcp/ri/ri_controller.h
- src/device/rdram/rdram.c
- src/device/rdram/rdram.h
- src/main/savestates.c
This patch fixes the RDRAM initialization of mupen64plus-core, it allows [libdragon IPL](https://github.com/DragonMinded/libdragon/tree/trunk/boot) to boot.
Before this patch, the attached n64-systemtest shows the following:
```
[CORE]  Initializing 4 RDRAM modules for a total of 8 MB
[CORE]  Starting R4300 emulator: Pure Interpreter
[CORE]  IS64: Libdragon IPL3     
[CORE]  IS64: rdram_reg_init: IO version  00000002   
[CORE]  IS64: Total memory:   00000000   
[CORE]  IS64: stage2  B0001C70    000007E8   
```
After this patch it successfully sees the RDRAM modules:
```
[CORE]  Initializing 4 RDRAM modules for a total of 8 MB
[CORE]  Starting R4300 emulator: Pure Interpreter
[CORE]  IS64: Libdragon IPL3     
[CORE]  IS64: rdram_reg_init: IO version  00000002   
[CORE]  IS64: Chip: …
```
> Fix RDRAM initialization

- src/device/rcp/ai/ai_controller.c
- src/device/rcp/ai/ai_controller.h
- src/device/rcp/mi/mi_controller.h
- src/device/rcp/pi/pi_controller.c
- src/device/rcp/pi/pi_controller.h
- src/device/rcp/rdp/rdp_core.c
- src/device/rcp/rdp/rdp_core.h
- src/device/rcp/ri/ri_controller.h
- src/device/rcp/rsp/rsp_core.c
- src/device/rcp/rsp/rsp_core.h
- src/device/rcp/si/si_controller.c
- src/device/rcp/si/si_controller.h
- src/device/rcp/vi/vi_controller.c
- src/device/rcp/vi/vi_controller.h
- src/device/rdram/rdram.c
This patch is based on the ares PR which implements the same thing: https://github.com/ares-emulator/ares/pull/1344
We also sadly still need bounds checking for some register read/writes.
This also adds a bounds check for RDRAM register read/writes, which, according to n64brew, reads 0 when out-of-bounds:
https://n64brew.dev/wiki/RDRAM#RDRAM_registers
It also mentions the following:
> RDRAM registers mirror every 0x40 bytes (16 words). Register numbers 10 to 15 all produce 0 when read. Above 0x200 (register number 128) the Device Type mirrors are replaced with the Row register. 
I don't think any game relies on that so that's a TODO for the future.
Fixes #1121
> Implement register mirroring

- src/device/cart/cart.c
- src/device/cart/cart_rom.c
- src/device/cart/flashram.c
- src/device/cart/flashram.h
- src/device/cart/sram.c
- src/device/cart/sram.h
This patch is a backport from Logan's simple64.
Fixes #1083
> Add bounds checking to some DMA operations

- src/main/eventloop.c
With  #1094 merged this header is no longer used.
> Remove unused SDL_syswm header

- src/device/r4300/new_dynarec/arm/assem_arm.c
- src/device/r4300/new_dynarec/arm64/assem_arm64.c
- src/device/r4300/new_dynarec/new_dynarec.c
- src/device/r4300/new_dynarec/x64/assem_x64.c
Fixes #1050 
Fixes #1051
Fixes #1052
cc @m4xw for the new_dynarec changes
cc @loganmc10 for the register bounds check changes
> Misc crash fixes

- tools/install_binary_bundle.sh
install.sh does not automatically link libmupen64plus.so.2.* to libmupen64plus.so.2, resulting in an error when trying to execute the binary after running install.sh
create a symbolic link after installing libmupen64plus.so.2.* to the library directory
> Add a symbolic link from libmupen64plus.so.2.* to libmupen64plus.so.2

- projects/unix/Makefile
The Makefile checks for `clang` as C compiler. This may not work using MSYS2 CLANG64, as the compiler may disguise itself as gcc. See: https://github.com/msys2/MINGW-packages/issues/9417#issuecomment-901039537
My idea for a fix is to check for the $MSYSTEM variable one way or another.
`ifeq ($(shell printenv MSYSTEM), CLANG64)` or `ifeq ($(shell echo $(MSYSTEM)), CLANG64)`
> make: Fix compiling with MSYS2 CLANG64
